#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SKAR_Skeleton_Anim

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_SKAR_Skeleton_Anim.ABP_SKAR_Skeleton_Anim_C
// 0x0100 (0x03D0 - 0x02D0)
class UABP_SKAR_Skeleton_Anim_C final : public UGunAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02D8(0x0030)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0308(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0350(0x0080)()

public:
	void ExecuteUbergraph_ABP_SKAR_Skeleton_Anim(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_SKAR_Skeleton_Anim_C">();
	}
	static class UABP_SKAR_Skeleton_Anim_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_SKAR_Skeleton_Anim_C>();
	}
};
static_assert(alignof(UABP_SKAR_Skeleton_Anim_C) == 0x000010, "Wrong alignment on UABP_SKAR_Skeleton_Anim_C");
static_assert(sizeof(UABP_SKAR_Skeleton_Anim_C) == 0x0003D0, "Wrong size on UABP_SKAR_Skeleton_Anim_C");
static_assert(offsetof(UABP_SKAR_Skeleton_Anim_C, UberGraphFrame) == 0x0002D0, "Member 'UABP_SKAR_Skeleton_Anim_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_SKAR_Skeleton_Anim_C, AnimGraphNode_Root) == 0x0002D8, "Member 'UABP_SKAR_Skeleton_Anim_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_SKAR_Skeleton_Anim_C, AnimGraphNode_Slot) == 0x000308, "Member 'UABP_SKAR_Skeleton_Anim_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UABP_SKAR_Skeleton_Anim_C, AnimGraphNode_SequencePlayer) == 0x000350, "Member 'UABP_SKAR_Skeleton_Anim_C::AnimGraphNode_SequencePlayer' has a wrong offset!");

}

