#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AL_SubwayVents

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AL_SubwayVents.AL_SubwayVents_C
// 0x0000 (0x0100 - 0x0100)
class UAL_SubwayVents_C final : public UArcadeLevelAsset
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AL_SubwayVents_C">();
	}
	static class UAL_SubwayVents_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAL_SubwayVents_C>();
	}
};
static_assert(alignof(UAL_SubwayVents_C) == 0x000008, "Wrong alignment on UAL_SubwayVents_C");
static_assert(sizeof(UAL_SubwayVents_C) == 0x000100, "Wrong size on UAL_SubwayVents_C");

}

