#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_TYVCLibrary

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.GetCurrentChapter
// 0x0038 (0x0038 - 0x0000)
struct BFL_TYVCLibrary_C_GetCurrentChapter final
{
public:
	class AActor*                                 Context;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AChapter*                               OutChapter;                                        // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     K2Node_DynamicCast_AsTYVCGame_Mode_BP;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AChapter*                               CallFunc_GetCurrentChapter_ReturnValue;            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BFL_TYVCLibrary_C_GetCurrentChapter) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_GetCurrentChapter");
static_assert(sizeof(BFL_TYVCLibrary_C_GetCurrentChapter) == 0x000038, "Wrong size on BFL_TYVCLibrary_C_GetCurrentChapter");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, Context) == 0x000000, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::Context' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, __WorldContext) == 0x000008, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, OutChapter) == 0x000010, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::OutChapter' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, CallFunc_GetGameMode_ReturnValue) == 0x000018, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, K2Node_DynamicCast_AsTYVCGame_Mode_BP) == 0x000020, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::K2Node_DynamicCast_AsTYVCGame_Mode_BP' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCurrentChapter, CallFunc_GetCurrentChapter_ReturnValue) == 0x000030, "Member 'BFL_TYVCLibrary_C_GetCurrentChapter::CallFunc_GetCurrentChapter_ReturnValue' has a wrong offset!");

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.GetCampaignManager
// 0x0030 (0x0030 - 0x0000)
struct BFL_TYVCLibrary_C_GetCampaignManager final
{
public:
	class AActor*                                 Context;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACampaignManager*                       OutCM;                                             // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     K2Node_DynamicCast_AsTYVCGame_Mode_BP;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BFL_TYVCLibrary_C_GetCampaignManager) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_GetCampaignManager");
static_assert(sizeof(BFL_TYVCLibrary_C_GetCampaignManager) == 0x000030, "Wrong size on BFL_TYVCLibrary_C_GetCampaignManager");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, Context) == 0x000000, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::Context' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, __WorldContext) == 0x000008, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, OutCM) == 0x000010, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::OutCM' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, CallFunc_GetGameMode_ReturnValue) == 0x000018, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, K2Node_DynamicCast_AsTYVCGame_Mode_BP) == 0x000020, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::K2Node_DynamicCast_AsTYVCGame_Mode_BP' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetCampaignManager, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BFL_TYVCLibrary_C_GetCampaignManager::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.GetTYVCGameMode
// 0x0030 (0x0030 - 0x0000)
struct BFL_TYVCLibrary_C_GetTYVCGameMode final
{
public:
	class UObject*                                Context;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     NewParam;                                          // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     K2Node_DynamicCast_AsTYVCGame_Mode_BP;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BFL_TYVCLibrary_C_GetTYVCGameMode) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_GetTYVCGameMode");
static_assert(sizeof(BFL_TYVCLibrary_C_GetTYVCGameMode) == 0x000030, "Wrong size on BFL_TYVCLibrary_C_GetTYVCGameMode");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, Context) == 0x000000, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::Context' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, __WorldContext) == 0x000008, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, NewParam) == 0x000010, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::NewParam' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, CallFunc_GetGameMode_ReturnValue) == 0x000018, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, K2Node_DynamicCast_AsTYVCGame_Mode_BP) == 0x000020, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::K2Node_DynamicCast_AsTYVCGame_Mode_BP' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetTYVCGameMode, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BFL_TYVCLibrary_C_GetTYVCGameMode::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.GetGameMenu
// 0x0038 (0x0038 - 0x0000)
struct BFL_TYVCLibrary_C_GetGameMenu final
{
public:
	class UObject*                                Context;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      OutMenu;                                           // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameMenuWidget*                        CallFunc_GetGameMenu_ReturnValue;                  // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      K2Node_DynamicCast_AsWBP_Main_Menu_V3;             // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BFL_TYVCLibrary_C_GetGameMenu) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_GetGameMenu");
static_assert(sizeof(BFL_TYVCLibrary_C_GetGameMenu) == 0x000038, "Wrong size on BFL_TYVCLibrary_C_GetGameMenu");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, Context) == 0x000000, "Member 'BFL_TYVCLibrary_C_GetGameMenu::Context' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, __WorldContext) == 0x000008, "Member 'BFL_TYVCLibrary_C_GetGameMenu::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, OutMenu) == 0x000010, "Member 'BFL_TYVCLibrary_C_GetGameMenu::OutMenu' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, CallFunc_GetTYVCGameMode_NewParam) == 0x000018, "Member 'BFL_TYVCLibrary_C_GetGameMenu::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, CallFunc_GetGameMenu_ReturnValue) == 0x000020, "Member 'BFL_TYVCLibrary_C_GetGameMenu::CallFunc_GetGameMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, K2Node_DynamicCast_AsWBP_Main_Menu_V3) == 0x000028, "Member 'BFL_TYVCLibrary_C_GetGameMenu::K2Node_DynamicCast_AsWBP_Main_Menu_V3' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_GetGameMenu, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BFL_TYVCLibrary_C_GetGameMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.UntoggleAllChildren
// 0x0048 (0x0048 - 0x0000)
struct BFL_TYVCLibrary_C_UntoggleAllChildren final
{
public:
	class UPanelWidget*                           ParentWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      K2Node_DynamicCast_AsWBP_Adam_Button;              // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BFL_TYVCLibrary_C_UntoggleAllChildren) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_UntoggleAllChildren");
static_assert(sizeof(BFL_TYVCLibrary_C_UntoggleAllChildren) == 0x000048, "Wrong size on BFL_TYVCLibrary_C_UntoggleAllChildren");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, ParentWidget) == 0x000000, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::ParentWidget' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, __WorldContext) == 0x000008, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, CallFunc_GetAllChildren_ReturnValue) == 0x000010, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, Temp_int_Array_Index_Variable) == 0x000020, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, CallFunc_Array_Length_ReturnValue) == 0x000024, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, CallFunc_Array_Get_Item) == 0x000028, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, K2Node_DynamicCast_AsWBP_Adam_Button) == 0x000030, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::K2Node_DynamicCast_AsWBP_Adam_Button' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, Temp_int_Loop_Counter_Variable) == 0x00003C, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_UntoggleAllChildren, CallFunc_Add_IntInt_ReturnValue) == 0x000044, "Member 'BFL_TYVCLibrary_C_UntoggleAllChildren::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function BFL_TYVCLibrary.BFL_TYVCLibrary_C.SpawnEmitter
// 0x0078 (0x0078 - 0x0000)
struct BFL_TYVCLibrary_C_SpawnEmitter final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        SimpleFXEmitterTemplate;                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        EmitterTemplate;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Rotation;                                          // 0x0024(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                Scale;                                             // 0x0030(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAutoDestroy;                                      // 0x003C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EPSCPoolMethod                                PoolingMethod;                                     // 0x003D(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAutoActivateSystem;                               // 0x003E(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F[0x1];                                       // 0x003F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               ReturnValue;                                       // 0x0048(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_SelectObject_ReturnValue;                 // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        K2Node_DynamicCast_AsParticle_System;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BFL_TYVCLibrary_C_SpawnEmitter) == 0x000008, "Wrong alignment on BFL_TYVCLibrary_C_SpawnEmitter");
static_assert(sizeof(BFL_TYVCLibrary_C_SpawnEmitter) == 0x000078, "Wrong size on BFL_TYVCLibrary_C_SpawnEmitter");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, WorldContextObject) == 0x000000, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::WorldContextObject' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, SimpleFXEmitterTemplate) == 0x000008, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::SimpleFXEmitterTemplate' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, EmitterTemplate) == 0x000010, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::EmitterTemplate' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, Location) == 0x000018, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::Location' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, Rotation) == 0x000024, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::Rotation' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, Scale) == 0x000030, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::Scale' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, bAutoDestroy) == 0x00003C, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::bAutoDestroy' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, PoolingMethod) == 0x00003D, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::PoolingMethod' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, bAutoActivateSystem) == 0x00003E, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::bAutoActivateSystem' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, __WorldContext) == 0x000040, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::__WorldContext' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, ReturnValue) == 0x000048, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, CallFunc_GetTYVCGameMode_NewParam) == 0x000050, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, CallFunc_SelectObject_ReturnValue) == 0x000058, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::CallFunc_SelectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, K2Node_DynamicCast_AsParticle_System) == 0x000060, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::K2Node_DynamicCast_AsParticle_System' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BFL_TYVCLibrary_C_SpawnEmitter, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000070, "Member 'BFL_TYVCLibrary_C_SpawnEmitter::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");

}

