#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PoolManager

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PoolManager.BP_PoolManager_C
// 0x0000 (0x0318 - 0x0318)
class ABP_PoolManager_C final : public APoolManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PoolManager_C">();
	}
	static class ABP_PoolManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PoolManager_C>();
	}
};
static_assert(alignof(ABP_PoolManager_C) == 0x000008, "Wrong alignment on ABP_PoolManager_C");
static_assert(sizeof(ABP_PoolManager_C) == 0x000318, "Wrong size on ABP_PoolManager_C");

}

