#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_SetCrouchState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BT_SetCrouchState.BT_SetCrouchState_C
// 0x0010 (0x00B8 - 0x00A8)
class UBT_SetCrouchState_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          ShouldCrouch;                                      // 0x00B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BT_SetCrouchState(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BT_SetCrouchState_C">();
	}
	static class UBT_SetCrouchState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBT_SetCrouchState_C>();
	}
};
static_assert(alignof(UBT_SetCrouchState_C) == 0x000008, "Wrong alignment on UBT_SetCrouchState_C");
static_assert(sizeof(UBT_SetCrouchState_C) == 0x0000B8, "Wrong size on UBT_SetCrouchState_C");
static_assert(offsetof(UBT_SetCrouchState_C, UberGraphFrame) == 0x0000A8, "Member 'UBT_SetCrouchState_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBT_SetCrouchState_C, ShouldCrouch) == 0x0000B0, "Member 'UBT_SetCrouchState_C::ShouldCrouch' has a wrong offset!");

}

