#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTD_IsDistanceBaseOfFireValid

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTD_IsDistanceBaseOfFireValid.BTD_IsDistanceBaseOfFireValid_C
// 0x0058 (0x00F8 - 0x00A0)
class UBTD_IsDistanceBaseOfFireValid_C final : public UBTDecorator_BlueprintBase
{
public:
	float                                         Distance;                                          // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlackboardKeySelector                 FirePositionKey;                                   // 0x00A8(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 WasForcedToMoveKey;                                // 0x00D0(0x0028)(Edit, BlueprintVisible)

public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTD_IsDistanceBaseOfFireValid_C">();
	}
	static class UBTD_IsDistanceBaseOfFireValid_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTD_IsDistanceBaseOfFireValid_C>();
	}
};
static_assert(alignof(UBTD_IsDistanceBaseOfFireValid_C) == 0x000008, "Wrong alignment on UBTD_IsDistanceBaseOfFireValid_C");
static_assert(sizeof(UBTD_IsDistanceBaseOfFireValid_C) == 0x0000F8, "Wrong size on UBTD_IsDistanceBaseOfFireValid_C");
static_assert(offsetof(UBTD_IsDistanceBaseOfFireValid_C, Distance) == 0x0000A0, "Member 'UBTD_IsDistanceBaseOfFireValid_C::Distance' has a wrong offset!");
static_assert(offsetof(UBTD_IsDistanceBaseOfFireValid_C, FirePositionKey) == 0x0000A8, "Member 'UBTD_IsDistanceBaseOfFireValid_C::FirePositionKey' has a wrong offset!");
static_assert(offsetof(UBTD_IsDistanceBaseOfFireValid_C, WasForcedToMoveKey) == 0x0000D0, "Member 'UBTD_IsDistanceBaseOfFireValid_C::WasForcedToMoveKey' has a wrong offset!");

}

