#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LaserRev

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass LaserRev.LaserRev_C
// 0x0010 (0x06F0 - 0x06E0)
class ALaserRev_C final : public AWeaponBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_AmmoInd_C*                          BP_AmmoInd1;                                       // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LaserRev(int32 EntryPoint);
	void Randomize();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LaserRev_C">();
	}
	static class ALaserRev_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALaserRev_C>();
	}
};
static_assert(alignof(ALaserRev_C) == 0x000010, "Wrong alignment on ALaserRev_C");
static_assert(sizeof(ALaserRev_C) == 0x0006F0, "Wrong size on ALaserRev_C");
static_assert(offsetof(ALaserRev_C, UberGraphFrame) == 0x0006E0, "Member 'ALaserRev_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ALaserRev_C, BP_AmmoInd1) == 0x0006E8, "Member 'ALaserRev_C::BP_AmmoInd1' has a wrong offset!");

}

