#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MagShotgun

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MagShotgun.MagShotgun_C
// 0x0010 (0x06F0 - 0x06E0)
class AMagShotgun_C final : public AWeaponBase
{
public:
	class UBP_AmmoInd_C*                          BP_AmmoInd;                                        // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MagShotgun_C">();
	}
	static class AMagShotgun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMagShotgun_C>();
	}
};
static_assert(alignof(AMagShotgun_C) == 0x000010, "Wrong alignment on AMagShotgun_C");
static_assert(sizeof(AMagShotgun_C) == 0x0006F0, "Wrong size on AMagShotgun_C");
static_assert(offsetof(AMagShotgun_C, BP_AmmoInd) == 0x0006E0, "Member 'AMagShotgun_C::BP_AmmoInd' has a wrong offset!");

}

