#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP7

#include "Basic.hpp"


namespace SDK::Params
{

// Function MP7.MP7_C.ExecuteUbergraph_MP7
// 0x0004 (0x0004 - 0x0000)
struct MP7_C_ExecuteUbergraph_MP7 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MP7_C_ExecuteUbergraph_MP7) == 0x000004, "Wrong alignment on MP7_C_ExecuteUbergraph_MP7");
static_assert(sizeof(MP7_C_ExecuteUbergraph_MP7) == 0x000004, "Wrong size on MP7_C_ExecuteUbergraph_MP7");
static_assert(offsetof(MP7_C_ExecuteUbergraph_MP7, EntryPoint) == 0x000000, "Member 'MP7_C_ExecuteUbergraph_MP7::EntryPoint' has a wrong offset!");

}

