#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PortalRenderTargetMap

#include "Basic.hpp"

#include "PortalRenderTargetCollection_structs.hpp"


namespace SDK
{

// UserDefinedStruct PortalRenderTargetMap.PortalRenderTargetMap
// 0x0050 (0x0050 - 0x0000)
struct FPortalRenderTargetMap final
{
public:
	TMap<int32, struct FPortalRenderTargetCollection> RenderTargetsByDepth_7_77F891D14F0F8B1558564EB1678B5A6C; // 0x0000(0x0050)(Edit, BlueprintVisible)
};
static_assert(alignof(FPortalRenderTargetMap) == 0x000008, "Wrong alignment on FPortalRenderTargetMap");
static_assert(sizeof(FPortalRenderTargetMap) == 0x000050, "Wrong size on FPortalRenderTargetMap");
static_assert(offsetof(FPortalRenderTargetMap, RenderTargetsByDepth_7_77F891D14F0F8B1558564EB1678B5A6C) == 0x000000, "Member 'FPortalRenderTargetMap::RenderTargetsByDepth_7_77F891D14F0F8B1558564EB1678B5A6C' has a wrong offset!");

}

