#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PVW_StatueG1

#include "Basic.hpp"

#include "PVW_StatueBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PVW_StatueG1.PVW_StatueG1_C
// 0x0000 (0x0AB0 - 0x0AB0)
class APVW_StatueG1_C final : public APVW_StatueBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PVW_StatueG1_C">();
	}
	static class APVW_StatueG1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APVW_StatueG1_C>();
	}
};
static_assert(alignof(APVW_StatueG1_C) == 0x000008, "Wrong alignment on APVW_StatueG1_C");
static_assert(sizeof(APVW_StatueG1_C) == 0x000AB0, "Wrong size on APVW_StatueG1_C");

}

