#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PVW_PaintingGman

#include "Basic.hpp"

#include "PVW_PaintingBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PVW_PaintingGman.PVW_PaintingGman_C
// 0x0000 (0x0AB0 - 0x0AB0)
class APVW_PaintingGman_C final : public APVW_PaintingBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PVW_PaintingGman_C">();
	}
	static class APVW_PaintingGman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APVW_PaintingGman_C>();
	}
};
static_assert(alignof(APVW_PaintingGman_C) == 0x000008, "Wrong alignment on APVW_PaintingGman_C");
static_assert(sizeof(APVW_PaintingGman_C) == 0x000AB0, "Wrong size on APVW_PaintingGman_C");

}

