#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RecoilShake_Mp7

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RecoilShake_Mp7.RecoilShake_Mp7_C
// 0x0000 (0x01B0 - 0x01B0)
class URecoilShake_Mp7_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RecoilShake_Mp7_C">();
	}
	static class URecoilShake_Mp7_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URecoilShake_Mp7_C>();
	}
};
static_assert(alignof(URecoilShake_Mp7_C) == 0x000010, "Wrong alignment on URecoilShake_Mp7_C");
static_assert(sizeof(URecoilShake_Mp7_C) == 0x0001B0, "Wrong size on URecoilShake_Mp7_C");

}

