#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SquadTask_InvalidateModel

#include "Basic.hpp"


namespace SDK::Params
{

// Function SquadTask_InvalidateModel.SquadTask_InvalidateModel_C.ExecuteUbergraph_SquadTask_InvalidateModel
// 0x0020 (0x0020 - 0x0000)
struct SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASquad*                                 CallFunc_GetTheSquad_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel) == 0x000008, "Wrong alignment on SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel");
static_assert(sizeof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel) == 0x000020, "Wrong size on SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel");
static_assert(offsetof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel, EntryPoint) == 0x000000, "Member 'SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel::EntryPoint' has a wrong offset!");
static_assert(offsetof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel, K2Node_Event_OwnerActor) == 0x000008, "Member 'SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel::K2Node_Event_OwnerActor' has a wrong offset!");
static_assert(offsetof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel, CallFunc_GetTYVCGameMode_NewParam) == 0x000010, "Member 'SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel, CallFunc_GetTheSquad_ReturnValue) == 0x000018, "Member 'SquadTask_InvalidateModel_C_ExecuteUbergraph_SquadTask_InvalidateModel::CallFunc_GetTheSquad_ReturnValue' has a wrong offset!");

// Function SquadTask_InvalidateModel.SquadTask_InvalidateModel_C.ReceiveExecute
// 0x0008 (0x0008 - 0x0000)
struct SquadTask_InvalidateModel_C_ReceiveExecute final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SquadTask_InvalidateModel_C_ReceiveExecute) == 0x000008, "Wrong alignment on SquadTask_InvalidateModel_C_ReceiveExecute");
static_assert(sizeof(SquadTask_InvalidateModel_C_ReceiveExecute) == 0x000008, "Wrong size on SquadTask_InvalidateModel_C_ReceiveExecute");
static_assert(offsetof(SquadTask_InvalidateModel_C_ReceiveExecute, OwnerActor) == 0x000000, "Member 'SquadTask_InvalidateModel_C_ReceiveExecute::OwnerActor' has a wrong offset!");

}

