#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_SetupStandardCombat

#include "Basic.hpp"


namespace SDK::Params
{

// Function ST_SetupStandardCombat.ST_SetupStandardCombat_C.ExecuteUbergraph_ST_SetupStandardCombat
// 0x0040 (0x0040 - 0x0000)
struct ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_GetOuterObject_ReturnValue;               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USquadBT*                               K2Node_DynamicCast_AsSquad_BT;                     // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ANPCController*                         CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat) == 0x000008, "Wrong alignment on ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat");
static_assert(sizeof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat) == 0x000040, "Wrong size on ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, EntryPoint) == 0x000000, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::EntryPoint' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, Temp_int_Array_Index_Variable) == 0x000004, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, K2Node_Event_OwnerActor) == 0x000008, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::K2Node_Event_OwnerActor' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, CallFunc_GetOuterObject_ReturnValue) == 0x000018, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::CallFunc_GetOuterObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, K2Node_DynamicCast_AsSquad_BT) == 0x000020, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::K2Node_DynamicCast_AsSquad_BT' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, CallFunc_Array_Get_Item) == 0x000030, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'ST_SetupStandardCombat_C_ExecuteUbergraph_ST_SetupStandardCombat::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function ST_SetupStandardCombat.ST_SetupStandardCombat_C.ReceiveExecute
// 0x0008 (0x0008 - 0x0000)
struct ST_SetupStandardCombat_C_ReceiveExecute final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ST_SetupStandardCombat_C_ReceiveExecute) == 0x000008, "Wrong alignment on ST_SetupStandardCombat_C_ReceiveExecute");
static_assert(sizeof(ST_SetupStandardCombat_C_ReceiveExecute) == 0x000008, "Wrong size on ST_SetupStandardCombat_C_ReceiveExecute");
static_assert(offsetof(ST_SetupStandardCombat_C_ReceiveExecute, OwnerActor) == 0x000000, "Member 'ST_SetupStandardCombat_C_ReceiveExecute::OwnerActor' has a wrong offset!");

}

