#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VAL

#include "Basic.hpp"


namespace SDK::Params
{

// Function VAL.VAL_C.ExecuteUbergraph_VAL
// 0x0004 (0x0004 - 0x0000)
struct VAL_C_ExecuteUbergraph_VAL final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VAL_C_ExecuteUbergraph_VAL) == 0x000004, "Wrong alignment on VAL_C_ExecuteUbergraph_VAL");
static_assert(sizeof(VAL_C_ExecuteUbergraph_VAL) == 0x000004, "Wrong size on VAL_C_ExecuteUbergraph_VAL");
static_assert(offsetof(VAL_C_ExecuteUbergraph_VAL, EntryPoint) == 0x000000, "Member 'VAL_C_ExecuteUbergraph_VAL::EntryPoint' has a wrong offset!");

}

