#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CompassStyle_5

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_CompassStyle_5.W_CompassStyle_5_C
// 0x0008 (0x0268 - 0x0260)
class UW_CompassStyle_5_C final : public UUserWidget
{
public:
	class UW_CompassMaster_C*                     W_CompassMaster;                                   // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_CompassStyle_5_C">();
	}
	static class UW_CompassStyle_5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_CompassStyle_5_C>();
	}
};
static_assert(alignof(UW_CompassStyle_5_C) == 0x000008, "Wrong alignment on UW_CompassStyle_5_C");
static_assert(sizeof(UW_CompassStyle_5_C) == 0x000268, "Wrong size on UW_CompassStyle_5_C");
static_assert(offsetof(UW_CompassStyle_5_C, W_CompassMaster) == 0x000260, "Member 'UW_CompassStyle_5_C::W_CompassMaster' has a wrong offset!");

}

