#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SpeechBubbles

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "S_SpeechBubbleSettings_structs.hpp"


namespace SDK::Params
{

// Function W_SpeechBubbles.W_SpeechBubbles_C.ExecuteUbergraph_W_SpeechBubbles
// 0x0138 (0x0138 - 0x0000)
struct W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_SpeechBubble_C*                      K2Node_CustomEvent_SpeechBubble;                   // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_Speaker;                        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_CustomEvent_Text;                           // 0x0030(0x0018)(ConstParm)
	float                                         K2Node_CustomEvent_MaxRenderDistance;              // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_SpeechBubbleSettings                K2Node_CustomEvent_Settings;                       // 0x0050(0x0078)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASpeechBubbleLocation_C*                K2Node_CustomEvent_SpeechBubbleLocation;           // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      CallFunc_Create_ReturnValue;                       // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetFinalSize_Size;                        // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_ProjectWorldLocationToScreen_ScreenLocation; // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ProjectWorldLocationToScreen_ReturnValue; // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FA[0x2];                                       // 0x00FA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00FC(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles");
static_assert(sizeof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles) == 0x000138, "Wrong size on W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, EntryPoint) == 0x000000, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_SpeechBubble) == 0x000008, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_SpeechBubble' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_Array_RemoveItem_ReturnValue) == 0x000010, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_Event_IsDesignTime) == 0x000011, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_GetOwningPlayer_ReturnValue) == 0x000018, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000020, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_Speaker) == 0x000028, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_Speaker' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_Text) == 0x000030, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_Text' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_MaxRenderDistance) == 0x000048, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_MaxRenderDistance' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_Settings) == 0x000050, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_Settings' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_CustomEvent_SpeechBubbleLocation) == 0x0000C8, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_CustomEvent_SpeechBubbleLocation' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_Create_ReturnValue) == 0x0000D0, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_Array_Add_ReturnValue) == 0x0000D8, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000DC, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_GetFinalSize_Size) == 0x0000E8, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_GetFinalSize_Size' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_ProjectWorldLocationToScreen_ScreenLocation) == 0x0000F0, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_ProjectWorldLocationToScreen_ScreenLocation' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_ProjectWorldLocationToScreen_ReturnValue) == 0x0000F8, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_ProjectWorldLocationToScreen_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, CallFunc_BooleanOR_ReturnValue) == 0x0000F9, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_Event_MyGeometry) == 0x0000FC, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles, K2Node_Event_InDeltaTime) == 0x000134, "Member 'W_SpeechBubbles_C_ExecuteUbergraph_W_SpeechBubbles::K2Node_Event_InDeltaTime' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_SpeechBubbles_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_SpeechBubbles_C_PreConstruct) == 0x000001, "Wrong alignment on W_SpeechBubbles_C_PreConstruct");
static_assert(sizeof(W_SpeechBubbles_C_PreConstruct) == 0x000001, "Wrong size on W_SpeechBubbles_C_PreConstruct");
static_assert(offsetof(W_SpeechBubbles_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'W_SpeechBubbles_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.OnStopSpeaking
// 0x0008 (0x0008 - 0x0000)
struct W_SpeechBubbles_C_OnStopSpeaking final
{
public:
	class UW_SpeechBubble_C*                      SpeechBubble;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_OnStopSpeaking) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_OnStopSpeaking");
static_assert(sizeof(W_SpeechBubbles_C_OnStopSpeaking) == 0x000008, "Wrong size on W_SpeechBubbles_C_OnStopSpeaking");
static_assert(offsetof(W_SpeechBubbles_C_OnStopSpeaking, SpeechBubble) == 0x000000, "Member 'W_SpeechBubbles_C_OnStopSpeaking::SpeechBubble' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.Say
// 0x00A8 (0x00A8 - 0x0000)
struct W_SpeechBubbles_C_Say final
{
public:
	class AActor*                                 Speaker;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	float                                         MaxRenderDistance;                                 // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_SpeechBubbleSettings                Settings;                                          // 0x0028(0x0078)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASpeechBubbleLocation_C*                SpeechBubbleLocation;                              // 0x00A0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_Say) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_Say");
static_assert(sizeof(W_SpeechBubbles_C_Say) == 0x0000A8, "Wrong size on W_SpeechBubbles_C_Say");
static_assert(offsetof(W_SpeechBubbles_C_Say, Speaker) == 0x000000, "Member 'W_SpeechBubbles_C_Say::Speaker' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_Say, Text) == 0x000008, "Member 'W_SpeechBubbles_C_Say::Text' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_Say, MaxRenderDistance) == 0x000020, "Member 'W_SpeechBubbles_C_Say::MaxRenderDistance' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_Say, Settings) == 0x000028, "Member 'W_SpeechBubbles_C_Say::Settings' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_Say, SpeechBubbleLocation) == 0x0000A0, "Member 'W_SpeechBubbles_C_Say::SpeechBubbleLocation' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.Tick
// 0x003C (0x003C - 0x0000)
struct W_SpeechBubbles_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_Tick) == 0x000004, "Wrong alignment on W_SpeechBubbles_C_Tick");
static_assert(sizeof(W_SpeechBubbles_C_Tick) == 0x00003C, "Wrong size on W_SpeechBubbles_C_Tick");
static_assert(offsetof(W_SpeechBubbles_C_Tick, MyGeometry) == 0x000000, "Member 'W_SpeechBubbles_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_Tick, InDeltaTime) == 0x000038, "Member 'W_SpeechBubbles_C_Tick::InDeltaTime' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.TuneActiveBubbles
// 0x0068 (0x0068 - 0x0000)
struct W_SpeechBubbles_C_TuneActiveBubbles final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetFinalSize_Size;                        // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetFinalPosition_Position;                // 0x0034(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetFinalPosition_CanProject_;             // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_1;                        // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_1;                        // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x005C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_TuneActiveBubbles) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_TuneActiveBubbles");
static_assert(sizeof(W_SpeechBubbles_C_TuneActiveBubbles) == 0x000068, "Wrong size on W_SpeechBubbles_C_TuneActiveBubbles");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, Temp_int_Array_Index_Variable) == 0x000000, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, Temp_float_Variable) == 0x000004, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, Temp_bool_Variable) == 0x000008, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Array_Get_Item) == 0x000010, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_IsValid_ReturnValue) == 0x00001D, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_GetFinalSize_Size) == 0x000024, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_GetFinalSize_Size' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_BreakVector2D_X) == 0x00002C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_BreakVector2D_Y) == 0x000030, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_GetFinalPosition_Position) == 0x000034, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_GetFinalPosition_Position' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_GetFinalPosition_CanProject_) == 0x00003C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_GetFinalPosition_CanProject_' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000040, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, K2Node_Select_Default) == 0x000044, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_BreakVector2D_X_1) == 0x000048, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_BreakVector2D_Y_1) == 0x00004C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x000050, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000054, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000058, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_TuneActiveBubbles, CallFunc_MakeVector2D_ReturnValue) == 0x00005C, "Member 'W_SpeechBubbles_C_TuneActiveBubbles::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.GetSpeechBubbleByActor
// 0x0030 (0x0030 - 0x0000)
struct W_SpeechBubbles_C_GetSpeechBubbleByActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      SpeechBubbleWidget;                                // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_SpeechBubbles_C_GetSpeechBubbleByActor) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_GetSpeechBubbleByActor");
static_assert(sizeof(W_SpeechBubbles_C_GetSpeechBubbleByActor) == 0x000030, "Wrong size on W_SpeechBubbles_C_GetSpeechBubbleByActor");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, Actor) == 0x000000, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::Actor' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, SpeechBubbleWidget) == 0x000008, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::SpeechBubbleWidget' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, Temp_int_Array_Index_Variable) == 0x000010, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, CallFunc_Array_Get_Item) == 0x000020, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetSpeechBubbleByActor, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000029, "Member 'W_SpeechBubbles_C_GetSpeechBubbleByActor::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.GetFinalPosition
// 0x0128 (0x0128 - 0x0000)
struct W_SpeechBubbles_C_GetFinalPosition final
{
public:
	class AActor*                                 Speaker;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      SpeechBubble;                                      // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Position;                                          // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanProject_;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector2D_X;                          // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SignOfFloat_ReturnValue;                  // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue;                          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SignOfFloat_ReturnValue_1;                // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue_1;                        // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0044(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_ProjectWorldLocationToScreen_ScreenLocation; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ProjectWorldLocationToScreen_ReturnValue; // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector2D_X_1;                        // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_1;                        // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_2;                        // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_2;                        // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_2;          // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_3;          // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_3;                        // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_3;                        // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_3;        // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x009C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue_1;        // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue_1;              // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_4;          // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue;            // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_5;          // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMin_ReturnValue;                         // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue_1;                     // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue_1;          // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_4;        // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMin_ReturnValue_1;                       // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_3;        // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_5;        // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_ProjectWorldLocationToScreen_ScreenLocation_1; // 0x00FC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ProjectWorldLocationToScreen_ReturnValue_1; // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_4;                        // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_4;                        // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_Add_Vector2DVector2D_ReturnValue;         // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_GetFinalPosition) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_GetFinalPosition");
static_assert(sizeof(W_SpeechBubbles_C_GetFinalPosition) == 0x000128, "Wrong size on W_SpeechBubbles_C_GetFinalPosition");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, Speaker) == 0x000000, "Member 'W_SpeechBubbles_C_GetFinalPosition::Speaker' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, SpeechBubble) == 0x000008, "Member 'W_SpeechBubbles_C_GetFinalPosition::SpeechBubble' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, Position) == 0x000010, "Member 'W_SpeechBubbles_C_GetFinalPosition::Position' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CanProject_) == 0x000018, "Member 'W_SpeechBubbles_C_GetFinalPosition::CanProject_' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetOwningPlayer_ReturnValue) == 0x000020, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_X) == 0x00002C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_Y) == 0x000030, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_SignOfFloat_ReturnValue) == 0x000034, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_SignOfFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Abs_ReturnValue) == 0x000038, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_SignOfFloat_ReturnValue_1) == 0x00003C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_SignOfFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Abs_ReturnValue_1) == 0x000040, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Abs_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000044, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_ProjectWorldLocationToScreen_ScreenLocation) == 0x000050, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_ProjectWorldLocationToScreen_ScreenLocation' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_ProjectWorldLocationToScreen_ReturnValue) == 0x000058, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_ProjectWorldLocationToScreen_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_X_1) == 0x00005C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_Y_1) == 0x000060, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_X_2) == 0x000064, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_X_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_Y_2) == 0x000068, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_Y_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x00006C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000070, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x000074, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000078, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x00007C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue_2) == 0x000080, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000084, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x000088, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue_3) == 0x00008C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_X_3) == 0x000090, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_X_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_Y_3) == 0x000094, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_Y_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue_3) == 0x000098, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x00009C, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetOwningPlayerPawn_ReturnValue) == 0x0000A8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetOwningPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetOwningPlayerPawn_ReturnValue_1) == 0x0000B0, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetOwningPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetDistanceTo_ReturnValue) == 0x0000B8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetDistanceTo_ReturnValue_1) == 0x0000BC, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetDistanceTo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue_4) == 0x0000C0, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0000C4, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_FTrunc_ReturnValue) == 0x0000C8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_IntFloat_ReturnValue) == 0x0000CC, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_IntFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Divide_FloatFloat_ReturnValue_5) == 0x0000D0, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Divide_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_FMin_ReturnValue) == 0x0000D4, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_FTrunc_ReturnValue_1) == 0x0000D8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_FTrunc_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x0000DC, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_IntFloat_ReturnValue_1) == 0x0000E0, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_IntFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue_4) == 0x0000E4, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_FMin_ReturnValue_1) == 0x0000E8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_FMin_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Subtract_FloatFloat_ReturnValue_3) == 0x0000EC, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Subtract_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0000F0, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Multiply_FloatFloat_ReturnValue_5) == 0x0000F8, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Multiply_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_ProjectWorldLocationToScreen_ScreenLocation_1) == 0x0000FC, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_ProjectWorldLocationToScreen_ScreenLocation_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_ProjectWorldLocationToScreen_ReturnValue_1) == 0x000104, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_ProjectWorldLocationToScreen_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_MakeVector2D_ReturnValue) == 0x000108, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_X_4) == 0x000110, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_X_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_BreakVector2D_Y_4) == 0x000114, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_BreakVector2D_Y_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_MakeVector2D_ReturnValue_1) == 0x000118, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalPosition, CallFunc_Add_Vector2DVector2D_ReturnValue) == 0x000120, "Member 'W_SpeechBubbles_C_GetFinalPosition::CallFunc_Add_Vector2DVector2D_ReturnValue' has a wrong offset!");

// Function W_SpeechBubbles.W_SpeechBubbles_C.GetFinalSize
// 0x00B8 (0x00B8 - 0x0000)
struct W_SpeechBubbles_C_GetFinalSize final
{
public:
	const class AActor*                           Speaker;                                           // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_SpeechBubble_C*                      SpeechBubble;                                      // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Size;                                              // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_1;                        // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_1;                        // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_2;                        // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_2;                        // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_3;                        // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_3;                        // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_2;          // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_3;          // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_4;                        // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_4;                        // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_3;        // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue_1;        // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_4;          // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_5;          // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue_1;                     // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue;            // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue_1;          // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMin_ReturnValue;                         // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMin_ReturnValue_1;                       // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_3;        // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_SpeechBubbles_C_GetFinalSize) == 0x000008, "Wrong alignment on W_SpeechBubbles_C_GetFinalSize");
static_assert(sizeof(W_SpeechBubbles_C_GetFinalSize) == 0x0000B8, "Wrong size on W_SpeechBubbles_C_GetFinalSize");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, Speaker) == 0x000000, "Member 'W_SpeechBubbles_C_GetFinalSize::Speaker' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, SpeechBubble) == 0x000008, "Member 'W_SpeechBubbles_C_GetFinalSize::SpeechBubble' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, Size) == 0x000010, "Member 'W_SpeechBubbles_C_GetFinalSize::Size' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_MakeVector2D_ReturnValue) == 0x000018, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_X) == 0x000020, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_Y) == 0x000024, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_X_1) == 0x000028, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_Y_1) == 0x00002C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_X_2) == 0x000030, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_X_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_Y_2) == 0x000034, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_Y_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_X_3) == 0x000038, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_X_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_Y_3) == 0x00003C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_Y_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000040, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000044, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x000048, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00004C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x000050, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue_2) == 0x000054, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000058, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x00005C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue_3) == 0x000060, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_X_4) == 0x000064, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_X_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_BreakVector2D_Y_4) == 0x000068, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_BreakVector2D_Y_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_FloatFloat_ReturnValue_3) == 0x00006C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_GetOwningPlayerPawn_ReturnValue) == 0x000070, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_GetOwningPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_GetOwningPlayerPawn_ReturnValue_1) == 0x000078, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_GetOwningPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_IsValid_ReturnValue) == 0x000080, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_GetDistanceTo_ReturnValue) == 0x000084, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue_4) == 0x000088, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Divide_FloatFloat_ReturnValue_5) == 0x00008C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Divide_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_FTrunc_ReturnValue) == 0x000090, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_FTrunc_ReturnValue_1) == 0x000094, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_FTrunc_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_IntFloat_ReturnValue) == 0x000098, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_IntFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Multiply_IntFloat_ReturnValue_1) == 0x00009C, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Multiply_IntFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_FMin_ReturnValue) == 0x0000A0, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_FMin_ReturnValue_1) == 0x0000A4, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_FMin_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x0000A8, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_Subtract_FloatFloat_ReturnValue_3) == 0x0000AC, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_Subtract_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_SpeechBubbles_C_GetFinalSize, CallFunc_MakeVector2D_ReturnValue_1) == 0x0000B0, "Member 'W_SpeechBubbles_C_GetFinalSize::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");

}

