#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBO_Row

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBO_Row.WBO_Row_C.ExecuteUbergraph_WBO_Row
// 0x00F8 (0x00F8 - 0x0000)
struct WBO_Row_C_ExecuteUbergraph_WBO_Row final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B[0x1];                                        // 0x000B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_2;                             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_3;                             // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelWidget*                           CallFunc_GetParent_ReturnValue;                    // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelWidget*                           K2Node_DynamicCast_AsPanel_Widget;                 // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetChildIndex_ReturnValue;                // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F[0x1];                                       // 0x003F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStyledAxisMapping_C*                   K2Node_DynamicCast_AsStyled_Axis_Mapping;          // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStyledActionMapping_C*                 K2Node_DynamicCast_AsStyled_Action_Mapping;        // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStyledBindCaptureButton_C*             K2Node_DynamicCast_AsStyled_Bind_Capture_Button;   // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStyledBindCaptureButton_C*             K2Node_DynamicCast_AsStyled_Bind_Capture_Button_1; // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_AdamButton_C*                      K2Node_DynamicCast_AsWBP_Adam_Button;              // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_AdamSmallToggleButton_C*           K2Node_DynamicCast_AsWBP_Adam_Small_Toggle_Button; // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A3[0x1];                                       // 0x00A3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x00A4(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x00AC(0x0008)(NoDestructor)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;      // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHorizontalBoxSlot*                     CallFunc_SlotAsHorizontalBoxSlot_ReturnValue_1;    // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_2;                           // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x00E4(0x0008)(NoDestructor)
	float                                         K2Node_Select_Default_3;                           // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize_1;                // 0x00F0(0x0008)(NoDestructor)
};
static_assert(alignof(WBO_Row_C_ExecuteUbergraph_WBO_Row) == 0x000008, "Wrong alignment on WBO_Row_C_ExecuteUbergraph_WBO_Row");
static_assert(sizeof(WBO_Row_C_ExecuteUbergraph_WBO_Row) == 0x0000F8, "Wrong size on WBO_Row_C_ExecuteUbergraph_WBO_Row");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, EntryPoint) == 0x000000, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_bool_Variable) == 0x000004, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_byte_Variable) == 0x000005, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_byte_Variable_1) == 0x000006, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_bool_Variable_1) == 0x000007, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_byte_Variable_2) == 0x000008, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_byte_Variable_3) == 0x000009, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_bool_Variable_2) == 0x00000A, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_float_Variable) == 0x00000C, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_float_Variable_1) == 0x000010, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_bool_Variable_3) == 0x000014, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_float_Variable_2) == 0x000018, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_float_Variable_2' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, Temp_float_Variable_3) == 0x00001C, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::Temp_float_Variable_3' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetParent_ReturnValue) == 0x000020, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsPanel_Widget) == 0x000028, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsPanel_Widget' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetChildIndex_ReturnValue) == 0x000034, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetChildIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_Percent_IntInt_ReturnValue) == 0x000038, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_Greater_IntInt_ReturnValue) == 0x00003C, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_BooleanOR_ReturnValue) == 0x00003D, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Select_Default) == 0x00003E, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetChildAt_ReturnValue) == 0x000040, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsStyled_Axis_Mapping) == 0x000048, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsStyled_Axis_Mapping' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsStyled_Action_Mapping) == 0x000058, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsStyled_Action_Mapping' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_2) == 0x000060, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsStyled_Bind_Capture_Button) == 0x000068, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsStyled_Bind_Capture_Button' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_3) == 0x000070, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsStyled_Bind_Capture_Button_1) == 0x000078, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsStyled_Bind_Capture_Button_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_4) == 0x000080, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsWBP_Adam_Button) == 0x000088, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsWBP_Adam_Button' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_5) == 0x000090, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_AsWBP_Adam_Small_Toggle_Button) == 0x000098, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_AsWBP_Adam_Small_Toggle_Button' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_DynamicCast_bSuccess_6) == 0x0000A0, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Select_Default_1) == 0x0000A1, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Event_IsDesignTime) == 0x0000A2, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Event_InFocusEvent_1) == 0x0000A4, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Event_InFocusEvent_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Event_InFocusEvent) == 0x0000AC, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Event_InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetTYVCGameMode_NewParam) == 0x0000B8, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetTYVCGameMode_NewParam_1) == 0x0000C0, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_GetGameMenu_OutMenu) == 0x0000C8, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue) == 0x0000D0, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, CallFunc_SlotAsHorizontalBoxSlot_ReturnValue_1) == 0x0000D8, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::CallFunc_SlotAsHorizontalBoxSlot_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Select_Default_2) == 0x0000E0, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_MakeStruct_SlateChildSize) == 0x0000E4, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_Select_Default_3) == 0x0000EC, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(WBO_Row_C_ExecuteUbergraph_WBO_Row, K2Node_MakeStruct_SlateChildSize_1) == 0x0000F0, "Member 'WBO_Row_C_ExecuteUbergraph_WBO_Row::K2Node_MakeStruct_SlateChildSize_1' has a wrong offset!");

// Function WBO_Row.WBO_Row_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBO_Row_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBO_Row_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on WBO_Row_C_OnRemovedFromFocusPath");
static_assert(sizeof(WBO_Row_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on WBO_Row_C_OnRemovedFromFocusPath");
static_assert(offsetof(WBO_Row_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'WBO_Row_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function WBO_Row.WBO_Row_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBO_Row_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBO_Row_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on WBO_Row_C_OnAddedToFocusPath");
static_assert(sizeof(WBO_Row_C_OnAddedToFocusPath) == 0x000008, "Wrong size on WBO_Row_C_OnAddedToFocusPath");
static_assert(offsetof(WBO_Row_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'WBO_Row_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function WBO_Row.WBO_Row_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBO_Row_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBO_Row_C_PreConstruct) == 0x000001, "Wrong alignment on WBO_Row_C_PreConstruct");
static_assert(sizeof(WBO_Row_C_PreConstruct) == 0x000001, "Wrong size on WBO_Row_C_PreConstruct");
static_assert(offsetof(WBO_Row_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBO_Row_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

