#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PauseV3

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "ThankYouVeryCool_structs.hpp"


namespace SDK::Params
{

// Function WBP_PauseV3.WBP_PauseV3_C.ExecuteUbergraph_WBP_PauseV3
// 0x0168 (0x0168 - 0x0000)
struct WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CampaignDiff_C*                    CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(EDifficulty SelectedDiff)>     K2Node_CreateDelegate_OutputDelegate_1;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0040(0x0010)(ZeroConstructor, NoDestructor)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AThankYouVeryCoolGameMode*              K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCharacter_BP_Manny_C*            K2Node_DynamicCast_AsPlayer_Character_BP_Manny;    // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetCurrentTrackTitle_ReturnValue;         // 0x0090(0x0018)()
	EVoxelEditMod                                 K2Node_ComponentBoundEvent_OutNav;                 // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDifficulty                                   K2Node_CustomEvent_SelectedDiff;                   // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_1;                    // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_2;               // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDifficulty                                   CallFunc_GetDifficulty_ReturnValue;                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_3;               // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue_1;                // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AThankYouVeryCoolGameMode*              K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode_1; // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F2[0x6];                                       // 0x00F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_2;                    // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_3;                    // 0x0100(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0108(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0110(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_14D[0x3];                                      // 0x014D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_4;               // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetGamePaused_ReturnValue;                // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_5;               // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3) == 0x000008, "Wrong alignment on WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3");
static_assert(sizeof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3) == 0x000168, "Wrong size on WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, EntryPoint) == 0x000000, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_Create_ReturnValue) == 0x000008, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_CreateDelegate_OutputDelegate_1) == 0x000020, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_CreateDelegate_OutputDelegate_2) == 0x000030, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_CreateDelegate_OutputDelegate_3) == 0x000040, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMode_ReturnValue) == 0x000050, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetPlayerPawn_ReturnValue) == 0x000058, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode) == 0x000060, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_AsPlayer_Character_BP_Manny) == 0x000070, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_AsPlayer_Character_BP_Manny' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_bSuccess_1) == 0x000078, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMenu_OutMenu) == 0x000080, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam) == 0x000088, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetCurrentTrackTitle_ReturnValue) == 0x000090, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetCurrentTrackTitle_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_ComponentBoundEvent_OutNav) == 0x0000A8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_ComponentBoundEvent_OutNav' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam_1) == 0x0000B0, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_CustomEvent_SelectedDiff) == 0x0000B8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_CustomEvent_SelectedDiff' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMenu_OutMenu_1) == 0x0000C0, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMenu_OutMenu_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam_2) == 0x0000C8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam_2' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetDifficulty_ReturnValue) == 0x0000D0, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetDifficulty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam_3) == 0x0000D8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam_3' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMode_ReturnValue_1) == 0x0000E0, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMode_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode_1) == 0x0000E8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_DynamicCast_bSuccess_2) == 0x0000F0, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_Event_IsDesignTime) == 0x0000F1, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMenu_OutMenu_2) == 0x0000F8, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMenu_OutMenu_2' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetGameMenu_OutMenu_3) == 0x000100, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetGameMenu_OutMenu_3' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_AddChild_ReturnValue) == 0x000108, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_Event_MyGeometry) == 0x000110, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, K2Node_Event_InDeltaTime) == 0x000148, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_IsPlatform_ReturnValue) == 0x00014C, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam_4) == 0x000150, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam_4' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_SetGamePaused_ReturnValue) == 0x000158, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_SetGamePaused_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3, CallFunc_GetTYVCGameMode_NewParam_5) == 0x000160, "Member 'WBP_PauseV3_C_ExecuteUbergraph_WBP_PauseV3::CallFunc_GetTYVCGameMode_NewParam_5' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_PauseV3_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PauseV3_C_Tick) == 0x000004, "Wrong alignment on WBP_PauseV3_C_Tick");
static_assert(sizeof(WBP_PauseV3_C_Tick) == 0x00003C, "Wrong size on WBP_PauseV3_C_Tick");
static_assert(offsetof(WBP_PauseV3_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_PauseV3_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_PauseV3_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_PauseV3_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_PauseV3_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_PauseV3_C_PreConstruct");
static_assert(sizeof(WBP_PauseV3_C_PreConstruct) == 0x000001, "Wrong size on WBP_PauseV3_C_PreConstruct");
static_assert(offsetof(WBP_PauseV3_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_PauseV3_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.CustomEvent_0
// 0x0001 (0x0001 - 0x0000)
struct WBP_PauseV3_C_CustomEvent_0 final
{
public:
	EDifficulty                                   SelectedDiff;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PauseV3_C_CustomEvent_0) == 0x000001, "Wrong alignment on WBP_PauseV3_C_CustomEvent_0");
static_assert(sizeof(WBP_PauseV3_C_CustomEvent_0) == 0x000001, "Wrong size on WBP_PauseV3_C_CustomEvent_0");
static_assert(offsetof(WBP_PauseV3_C_CustomEvent_0, SelectedDiff) == 0x000000, "Member 'WBP_PauseV3_C_CustomEvent_0::SelectedDiff' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature final
{
public:
	EVoxelEditMod                                 OutNav;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature) == 0x000001, "Wrong alignment on WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature");
static_assert(sizeof(WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature) == 0x000001, "Wrong size on WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature");
static_assert(offsetof(WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature, OutNav) == 0x000000, "Member 'WBP_PauseV3_C_BndEvt__WBP_PauseV3_ShuffleBtn_K2Node_ComponentBoundEvent_7_Pressed__DelegateSignature::OutNav' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.NotifyShown
// 0x0060 (0x0060 - 0x0000)
struct WBP_PauseV3_C_NotifyShown final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESimState                                     Temp_byte_Variable_3;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_NDOC_C*>                    CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0008(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_NDOC_C*                            CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetCurrentTrackTitle_ReturnValue;         // 0x0038(0x0018)()
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PauseV3_C_NotifyShown) == 0x000008, "Wrong alignment on WBP_PauseV3_C_NotifyShown");
static_assert(sizeof(WBP_PauseV3_C_NotifyShown) == 0x000060, "Wrong size on WBP_PauseV3_C_NotifyShown");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, Temp_byte_Variable) == 0x000000, "Member 'WBP_PauseV3_C_NotifyShown::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, Temp_byte_Variable_1) == 0x000001, "Member 'WBP_PauseV3_C_NotifyShown::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, Temp_byte_Variable_2) == 0x000002, "Member 'WBP_PauseV3_C_NotifyShown::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, Temp_byte_Variable_3) == 0x000003, "Member 'WBP_PauseV3_C_NotifyShown::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000008, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_IsPlatform_ReturnValue) == 0x000018, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_Array_Get_Item) == 0x000020, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_GetTYVCGameMode_NewParam) == 0x000030, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_GetCurrentTrackTitle_ReturnValue) == 0x000038, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_GetCurrentTrackTitle_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, CallFunc_GetTYVCGameMode_NewParam_1) == 0x000050, "Member 'WBP_PauseV3_C_NotifyShown::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, K2Node_SwitchEnum_CmpSuccess) == 0x000058, "Member 'WBP_PauseV3_C_NotifyShown::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_NotifyShown, K2Node_Select_Default) == 0x000059, "Member 'WBP_PauseV3_C_NotifyShown::K2Node_Select_Default' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.GetColorAndOpacity_0
// 0x0068 (0x0068 - 0x0000)
struct WBP_PauseV3_C_GetColorAndOpacity_0 final
{
public:
	struct FSlateColor                            ReturnValue;                                       // 0x0000(0x0028)(Parm, OutParm, ReturnParm)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetVectorParameterValue_ReturnValue;      // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0040(0x0028)()
};
static_assert(alignof(WBP_PauseV3_C_GetColorAndOpacity_0) == 0x000008, "Wrong alignment on WBP_PauseV3_C_GetColorAndOpacity_0");
static_assert(sizeof(WBP_PauseV3_C_GetColorAndOpacity_0) == 0x000068, "Wrong size on WBP_PauseV3_C_GetColorAndOpacity_0");
static_assert(offsetof(WBP_PauseV3_C_GetColorAndOpacity_0, ReturnValue) == 0x000000, "Member 'WBP_PauseV3_C_GetColorAndOpacity_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_GetColorAndOpacity_0, CallFunc_MakeLiteralName_ReturnValue) == 0x000028, "Member 'WBP_PauseV3_C_GetColorAndOpacity_0::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_GetColorAndOpacity_0, CallFunc_GetVectorParameterValue_ReturnValue) == 0x000030, "Member 'WBP_PauseV3_C_GetColorAndOpacity_0::CallFunc_GetVectorParameterValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PauseV3_C_GetColorAndOpacity_0, K2Node_MakeStruct_SlateColor) == 0x000040, "Member 'WBP_PauseV3_C_GetColorAndOpacity_0::K2Node_MakeStruct_SlateColor' has a wrong offset!");

// Function WBP_PauseV3.WBP_PauseV3_C.NotifyHidden
// 0x0001 (0x0001 - 0x0000)
struct WBP_PauseV3_C_NotifyHidden final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_PauseV3_C_NotifyHidden) == 0x000001, "Wrong alignment on WBP_PauseV3_C_NotifyHidden");
static_assert(sizeof(WBP_PauseV3_C_NotifyHidden) == 0x000001, "Wrong size on WBP_PauseV3_C_NotifyHidden");
static_assert(offsetof(WBP_PauseV3_C_NotifyHidden, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'WBP_PauseV3_C_NotifyHidden::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

