#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LeaderboardEntry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_LeaderboardEntry.WBP_LeaderboardEntry_C.ExecuteUbergraph_WBP_LeaderboardEntry
// 0x0190 (0x0190 - 0x0000)
struct WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0020(0x0018)()
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0040(0x0018)()
	class FString                                 CallFunc_TimeSecondsToString_ReturnValue;          // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0068(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00A8(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00C0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x00D0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E8(0x0018)()
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0100(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_LeaderboardReport_C*               CallFunc_Create_ReturnValue;                       // 0x0110(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetMousePositionScaledByDPI_LocationX;    // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetMousePositionScaledByDPI_LocationY;    // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetMousePositionScaledByDPI_ReturnValue;  // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetFriendPersonaName_ReturnValue;         // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0158(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x0174(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x017C(0x0008)(NoDestructor)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_2;               // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry) == 0x000008, "Wrong alignment on WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry");
static_assert(sizeof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry) == 0x000190, "Wrong size on WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, EntryPoint) == 0x000000, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000018, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_IntToText_ReturnValue) == 0x000020, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000038, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000040, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_TimeSecondsToString_ReturnValue) == 0x000058, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_TimeSecondsToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, K2Node_MakeStruct_FormatArgumentData) == 0x000068, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_StringToText_ReturnValue) == 0x0000A8, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, K2Node_MakeArray_Array) == 0x0000C0, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0000D0, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Format_ReturnValue) == 0x0000E8, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_SelectColor_ReturnValue) == 0x000100, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_SelectColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Create_ReturnValue) == 0x000110, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetPlayerController_ReturnValue) == 0x000118, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetMousePositionScaledByDPI_LocationX) == 0x000120, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetMousePositionScaledByDPI_LocationX' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetMousePositionScaledByDPI_LocationY) == 0x000124, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetMousePositionScaledByDPI_LocationY' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetMousePositionScaledByDPI_ReturnValue) == 0x000128, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetMousePositionScaledByDPI_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetTYVCGameMode_NewParam) == 0x000130, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_MakeVector2D_ReturnValue) == 0x000138, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetTYVCGameMode_NewParam_1) == 0x000140, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetFriendPersonaName_ReturnValue) == 0x000148, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetFriendPersonaName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_Conv_StringToText_ReturnValue_2) == 0x000158, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_IsValid_ReturnValue_1) == 0x000170, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, K2Node_Event_InFocusEvent_1) == 0x000174, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::K2Node_Event_InFocusEvent_1' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, K2Node_Event_InFocusEvent) == 0x00017C, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::K2Node_Event_InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry, CallFunc_GetTYVCGameMode_NewParam_2) == 0x000188, "Member 'WBP_LeaderboardEntry_C_ExecuteUbergraph_WBP_LeaderboardEntry::CallFunc_GetTYVCGameMode_NewParam_2' has a wrong offset!");

// Function WBP_LeaderboardEntry.WBP_LeaderboardEntry_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_LeaderboardEntry_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_LeaderboardEntry_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on WBP_LeaderboardEntry_C_OnRemovedFromFocusPath");
static_assert(sizeof(WBP_LeaderboardEntry_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on WBP_LeaderboardEntry_C_OnRemovedFromFocusPath");
static_assert(offsetof(WBP_LeaderboardEntry_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_LeaderboardEntry_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_LeaderboardEntry.WBP_LeaderboardEntry_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_LeaderboardEntry_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_LeaderboardEntry_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on WBP_LeaderboardEntry_C_OnAddedToFocusPath");
static_assert(sizeof(WBP_LeaderboardEntry_C_OnAddedToFocusPath) == 0x000008, "Wrong size on WBP_LeaderboardEntry_C_OnAddedToFocusPath");
static_assert(offsetof(WBP_LeaderboardEntry_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_LeaderboardEntry_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_LeaderboardEntry.WBP_LeaderboardEntry_C.SetHoverState
// 0x0280 (0x0280 - 0x0000)
struct WBP_LeaderboardEntry_C_SetHoverState final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           K2Node_Select_Default;                             // 0x0008(0x0278)(ConstParm)
};
static_assert(alignof(WBP_LeaderboardEntry_C_SetHoverState) == 0x000008, "Wrong alignment on WBP_LeaderboardEntry_C_SetHoverState");
static_assert(sizeof(WBP_LeaderboardEntry_C_SetHoverState) == 0x000280, "Wrong size on WBP_LeaderboardEntry_C_SetHoverState");
static_assert(offsetof(WBP_LeaderboardEntry_C_SetHoverState, Temp_bool_Variable) == 0x000000, "Member 'WBP_LeaderboardEntry_C_SetHoverState::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_SetHoverState, CallFunc_BooleanOR_ReturnValue) == 0x000001, "Member 'WBP_LeaderboardEntry_C_SetHoverState::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_LeaderboardEntry_C_SetHoverState, K2Node_Select_Default) == 0x000008, "Member 'WBP_LeaderboardEntry_C_SetHoverState::K2Node_Select_Default' has a wrong offset!");

}

