#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EditorLoad

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"


namespace SDK::Params
{

// Function WBP_EditorLoad.WBP_EditorLoad_C.ExecuteUbergraph_WBP_EditorLoad
// 0x01F8 (0x01F8 - 0x0000)
struct WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_SaveStatus_C*                      CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_SaveStatus_C*                      CallFunc_Create_ReturnValue_1;                     // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_SteamUploading_C*                  CallFunc_Create_ReturnValue_2;                     // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23[0x5];                                       // 0x0023(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_1;                    // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_ComponentBoundEvent_Name;                   // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UArcadeLevelAssetWorkshop*              CallFunc_CopyLevel_ReturnValue;                    // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_2;                    // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool Success)>                 K2Node_CreateDelegate_OutputDelegate;              // 0x0068(0x0010)(ZeroConstructor, NoDestructor)
	struct FCustomCampaignStruct                  CallFunc_Get_Campaign_NewParam;                    // 0x0078(0x0088)()
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_2;               // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveCustomCampaign_ReturnValue;           // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomCampaignStruct                  CallFunc_Get_Campaign_NewParam_1;                  // 0x0110(0x0088)()
	bool                                          K2Node_CustomEvent_Success;                        // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_3;               // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_SaveStatus_C*                      CallFunc_Create_ReturnValue_3;                     // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveCustomCampaign_ReturnValue_1;         // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_2;                   // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_4;               // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetDistroName_ReturnValue;                // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad");
static_assert(sizeof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad) == 0x0001F8, "Wrong size on WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, EntryPoint) == 0x000000, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Create_ReturnValue) == 0x000008, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Create_ReturnValue_1) == 0x000010, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Create_ReturnValue_2) == 0x000018, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, K2Node_SwitchEnum_CmpSuccess) == 0x000020, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000021, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, K2Node_SwitchEnum_CmpSuccess_1) == 0x000022, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetGameMenu_OutMenu) == 0x000028, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetGameMenu_OutMenu_1) == 0x000030, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetGameMenu_OutMenu_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetTYVCGameMode_NewParam) == 0x000038, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetTYVCGameMode_NewParam_1) == 0x000040, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, K2Node_ComponentBoundEvent_Name) == 0x000048, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::K2Node_ComponentBoundEvent_Name' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_CopyLevel_ReturnValue) == 0x000058, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_CopyLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetGameMenu_OutMenu_2) == 0x000060, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetGameMenu_OutMenu_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, K2Node_CreateDelegate_OutputDelegate) == 0x000068, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Get_Campaign_NewParam) == 0x000078, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Get_Campaign_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetTYVCGameMode_NewParam_2) == 0x000100, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetTYVCGameMode_NewParam_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_SaveCustomCampaign_ReturnValue) == 0x000108, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_SaveCustomCampaign_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Get_Campaign_NewParam_1) == 0x000110, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Get_Campaign_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, K2Node_CustomEvent_Success) == 0x000198, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::K2Node_CustomEvent_Success' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetTYVCGameMode_NewParam_3) == 0x0001A0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetTYVCGameMode_NewParam_3' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_Create_ReturnValue_3) == 0x0001A8, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_SaveCustomCampaign_ReturnValue_1) == 0x0001B0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_SaveCustomCampaign_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_AddChild_ReturnValue) == 0x0001B8, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_AddChild_ReturnValue_1) == 0x0001C0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_AddChild_ReturnValue_2) == 0x0001C8, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_AddChild_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetPlayerController_ReturnValue) == 0x0001D0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetPlayerController_ReturnValue_1) == 0x0001D8, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetTYVCGameMode_NewParam_4) == 0x0001E0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetTYVCGameMode_NewParam_4' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_GetDistroName_ReturnValue) == 0x0001E8, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_GetDistroName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad, CallFunc_NotEqual_NameName_ReturnValue) == 0x0001F0, "Member 'WBP_EditorLoad_C_ExecuteUbergraph_WBP_EditorLoad::CallFunc_NotEqual_NameName_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.Uploaddone
// 0x0001 (0x0001 - 0x0000)
struct WBP_EditorLoad_C_Uploaddone final
{
public:
	bool                                          Success;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_EditorLoad_C_Uploaddone) == 0x000001, "Wrong alignment on WBP_EditorLoad_C_Uploaddone");
static_assert(sizeof(WBP_EditorLoad_C_Uploaddone) == 0x000001, "Wrong size on WBP_EditorLoad_C_Uploaddone");
static_assert(offsetof(WBP_EditorLoad_C_Uploaddone, Success) == 0x000000, "Member 'WBP_EditorLoad_C_Uploaddone::Success' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature");
static_assert(sizeof(WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature) == 0x000010, "Wrong size on WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature");
static_assert(offsetof(WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature, Name_0) == 0x000000, "Member 'WBP_EditorLoad_C_BndEvt__WBP_EditorLoad_WBP_NewLevel_C_1_K2Node_ComponentBoundEvent_4_NameChoosen__DelegateSignature::Name_0' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.NotifyShown
// 0x0068 (0x0068 - 0x0000)
struct WBP_EditorLoad_C_NotifyShown final
{
public:
	TDelegate<void(class UWBP_LockedLevel_DA_C* me)> K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UArcadeLevelAsset* OutLevel, class FText DisplayName)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UArcadeLevelAssetWorkshop*>      CallFunc_GetFoundEditorLevels_ReturnValue;         // 0x0030(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UArcadeLevelAssetWorkshop*              CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_LockedLevel_DA_C*                  CallFunc_Create_ReturnValue;                       // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_NotifyShown) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_NotifyShown");
static_assert(sizeof(WBP_EditorLoad_C_NotifyShown) == 0x000068, "Wrong size on WBP_EditorLoad_C_NotifyShown");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, K2Node_CreateDelegate_OutputDelegate) == 0x000000, "Member 'WBP_EditorLoad_C_NotifyShown::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, K2Node_CreateDelegate_OutputDelegate_1) == 0x000010, "Member 'WBP_EditorLoad_C_NotifyShown::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_GetTYVCGameMode_NewParam) == 0x000020, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, Temp_int_Loop_Counter_Variable) == 0x000028, "Member 'WBP_EditorLoad_C_NotifyShown::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_GetFoundEditorLevels_ReturnValue) == 0x000030, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_GetFoundEditorLevels_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_Less_IntInt_ReturnValue) == 0x000044, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, Temp_int_Array_Index_Variable) == 0x000048, "Member 'WBP_EditorLoad_C_NotifyShown::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_Array_Get_Item) == 0x000050, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_Create_ReturnValue) == 0x000058, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_NotifyShown, CallFunc_AddChild_ReturnValue) == 0x000060, "Member 'WBP_EditorLoad_C_NotifyShown::CallFunc_AddChild_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.LoadPressed
// 0x0010 (0x0010 - 0x0000)
struct WBP_EditorLoad_C_LoadPressed final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_LoadPressed) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_LoadPressed");
static_assert(sizeof(WBP_EditorLoad_C_LoadPressed) == 0x000010, "Wrong size on WBP_EditorLoad_C_LoadPressed");
static_assert(offsetof(WBP_EditorLoad_C_LoadPressed, Path) == 0x000000, "Member 'WBP_EditorLoad_C_LoadPressed::Path' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.VoxPressed
// 0x0018 (0x0018 - 0x0000)
struct WBP_EditorLoad_C_VoxPressed final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_VoxPressed) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_VoxPressed");
static_assert(sizeof(WBP_EditorLoad_C_VoxPressed) == 0x000018, "Wrong size on WBP_EditorLoad_C_VoxPressed");
static_assert(offsetof(WBP_EditorLoad_C_VoxPressed, Path) == 0x000000, "Member 'WBP_EditorLoad_C_VoxPressed::Path' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_VoxPressed, CallFunc_GetGameMenu_OutMenu) == 0x000010, "Member 'WBP_EditorLoad_C_VoxPressed::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.WBP_EditorLoad_AutoGenFunc
// 0x0018 (0x0018 - 0x0000)
struct WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UWBP_AdamButton_TextPayload_C*          me;                                                // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc");
static_assert(sizeof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc) == 0x000018, "Wrong size on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc, Path) == 0x000000, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc::Path' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc, me) == 0x000010, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc::me' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.WBP_EditorLoad_AutoGenFunc1
// 0x0028 (0x0028 - 0x0000)
struct WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1 final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UWBP_AdamButton_TextPayload_C*          me;                                                // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_1;                    // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1");
static_assert(sizeof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1) == 0x000028, "Wrong size on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1, Path) == 0x000000, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1::Path' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1, me) == 0x000010, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1::me' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1, CallFunc_GetGameMenu_OutMenu) == 0x000018, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1, CallFunc_GetGameMenu_OutMenu_1) == 0x000020, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc1::CallFunc_GetGameMenu_OutMenu_1' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.WBP_EditorLoad_AutoGenFunc2
// 0x0040 (0x0040 - 0x0000)
struct WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2 final
{
public:
	class UArcadeLevelAsset*                      OutLevel;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   DisplayName;                                       // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UArcadeLevelAssetWorkshop*              K2Node_DynamicCast_AsArcade_Level_Asset_Workshop;  // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu;                      // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenuV3_C*                      CallFunc_GetGameMenu_OutMenu_1;                    // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2");
static_assert(sizeof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2) == 0x000040, "Wrong size on WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, OutLevel) == 0x000000, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::OutLevel' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, DisplayName) == 0x000008, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::DisplayName' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, K2Node_DynamicCast_AsArcade_Level_Asset_Workshop) == 0x000020, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::K2Node_DynamicCast_AsArcade_Level_Asset_Workshop' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000029, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, CallFunc_GetGameMenu_OutMenu) == 0x000030, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::CallFunc_GetGameMenu_OutMenu' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2, CallFunc_GetGameMenu_OutMenu_1) == 0x000038, "Member 'WBP_EditorLoad_C_WBP_EditorLoad_AutoGenFunc2::CallFunc_GetGameMenu_OutMenu_1' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.hOVEREDwORLKSHOP
// 0x0010 (0x0010 - 0x0000)
struct WBP_EditorLoad_C_hOVEREDwORLKSHOP final
{
public:
	class UWBP_LockedLevel_DA_C*                  me;                                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             CallFunc_GetPreviewImage_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_hOVEREDwORLKSHOP) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_hOVEREDwORLKSHOP");
static_assert(sizeof(WBP_EditorLoad_C_hOVEREDwORLKSHOP) == 0x000010, "Wrong size on WBP_EditorLoad_C_hOVEREDwORLKSHOP");
static_assert(offsetof(WBP_EditorLoad_C_hOVEREDwORLKSHOP, me) == 0x000000, "Member 'WBP_EditorLoad_C_hOVEREDwORLKSHOP::me' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_hOVEREDwORLKSHOP, CallFunc_GetPreviewImage_ReturnValue) == 0x000008, "Member 'WBP_EditorLoad_C_hOVEREDwORLKSHOP::CallFunc_GetPreviewImage_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.Build CampaignLvl List
// 0x0060 (0x0060 - 0x0000)
struct WBP_EditorLoad_C_Build_CampaignLvl_List final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UArcadeLevelAsset* OutLevel, class FText DisplayName)> K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_LockedLevel_DA_C*                  CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UArcadeLevelAssetWorkshop*>      CallFunc_GetFoundEditorLevels_ReturnValue;         // 0x0038(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UArcadeLevelAssetWorkshop*              CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_EditorLoad_C_Build_CampaignLvl_List) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_Build_CampaignLvl_List");
static_assert(sizeof(WBP_EditorLoad_C_Build_CampaignLvl_List) == 0x000060, "Wrong size on WBP_EditorLoad_C_Build_CampaignLvl_List");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_Create_ReturnValue) == 0x000020, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_AddChild_ReturnValue) == 0x000028, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_GetTYVCGameMode_NewParam) == 0x000030, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_GetFoundEditorLevels_ReturnValue) == 0x000038, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_GetFoundEditorLevels_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_Array_Length_ReturnValue) == 0x000048, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_Array_Get_Item) == 0x000050, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Build_CampaignLvl_List, CallFunc_Less_IntInt_ReturnValue) == 0x000058, "Member 'WBP_EditorLoad_C_Build_CampaignLvl_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.Start Editing Cmpgn
// 0x0190 (0x0190 - 0x0000)
struct WBP_EditorLoad_C_Start_Editing_Cmpgn final
{
public:
	struct FCustomCampaignStruct                  Struct;                                            // 0x0000(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UWBP_CmpgnLvl_C*                        CallFunc_Create_ReturnValue;                       // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0090(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCustomCampaignText                    CallFunc_Array_Get_Item_1;                         // 0x00D0(0x0010)()
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCustomCampaign*                        CallFunc_SpawnObject_ReturnValue;                  // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_CmpgnLvl_C* This)>  K2Node_CreateDelegate_OutputDelegate;              // 0x00F8(0x0010)(ZeroConstructor, NoDestructor)
	class FString                                 CallFunc_GetCurrentCampaignDirLocal_ReturnValue;   // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_CmpgnLvl_C* NewParam)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0128(0x0010)(ZeroConstructor, NoDestructor)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_CmpgnLvl_C* me)>    K2Node_CreateDelegate_OutputDelegate_2;            // 0x0158(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UWBP_CmpgnLvl_C* NewParam)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x0168(0x0010)(ZeroConstructor, NoDestructor)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UArcadeLevelAssetWorkshop*              CallFunc_GetLevelFromCampaign_ReturnValue;         // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_Start_Editing_Cmpgn) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_Start_Editing_Cmpgn");
static_assert(sizeof(WBP_EditorLoad_C_Start_Editing_Cmpgn) == 0x000190, "Wrong size on WBP_EditorLoad_C_Start_Editing_Cmpgn");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, Struct) == 0x000000, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::Struct' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Create_ReturnValue) == 0x000088, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Conv_StringToText_ReturnValue) == 0x000090, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Array_Length_ReturnValue) == 0x0000A8, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, Temp_int_Array_Index_Variable) == 0x0000AC, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, Temp_int_Loop_Counter_Variable) == 0x0000B0, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Array_Get_Item) == 0x0000B8, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Less_IntInt_ReturnValue) == 0x0000C8, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Add_IntInt_ReturnValue) == 0x0000CC, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Array_Get_Item_1) == 0x0000D0, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000E0, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_SpawnObject_ReturnValue) == 0x0000E8, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_GetTYVCGameMode_NewParam) == 0x0000F0, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, K2Node_CreateDelegate_OutputDelegate) == 0x0000F8, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_GetCurrentCampaignDirLocal_ReturnValue) == 0x000108, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_GetCurrentCampaignDirLocal_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Concat_StrStr_ReturnValue) == 0x000118, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, K2Node_CreateDelegate_OutputDelegate_1) == 0x000128, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000138, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000148, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, K2Node_CreateDelegate_OutputDelegate_2) == 0x000158, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, K2Node_CreateDelegate_OutputDelegate_3) == 0x000168, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_AddChild_ReturnValue) == 0x000178, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_GetTYVCGameMode_NewParam_1) == 0x000180, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Start_Editing_Cmpgn, CallFunc_GetLevelFromCampaign_ReturnValue) == 0x000188, "Member 'WBP_EditorLoad_C_Start_Editing_Cmpgn::CallFunc_GetLevelFromCampaign_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.AddCmpgnLvl
// 0x0080 (0x0080 - 0x0000)
struct WBP_EditorLoad_C_AddCmpgnLvl final
{
public:
	class UArcadeLevelAsset*                      OutLevel;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   DisplayName;                                       // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UWBP_CmpgnLvl_C*                        CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_CmpgnLvl_C* This)>  K2Node_CreateDelegate_OutputDelegate;              // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UWBP_CmpgnLvl_C* NewParam)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UWBP_CmpgnLvl_C* me)>    K2Node_CreateDelegate_OutputDelegate_2;            // 0x0058(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UWBP_CmpgnLvl_C* NewParam)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x0068(0x0010)(ZeroConstructor, NoDestructor)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_AddCmpgnLvl) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_AddCmpgnLvl");
static_assert(sizeof(WBP_EditorLoad_C_AddCmpgnLvl) == 0x000080, "Wrong size on WBP_EditorLoad_C_AddCmpgnLvl");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, OutLevel) == 0x000000, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::OutLevel' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, DisplayName) == 0x000008, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::DisplayName' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, CallFunc_Create_ReturnValue) == 0x000020, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, CallFunc_Conv_TextToString_ReturnValue) == 0x000028, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, K2Node_CreateDelegate_OutputDelegate) == 0x000038, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, K2Node_CreateDelegate_OutputDelegate_1) == 0x000048, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, K2Node_CreateDelegate_OutputDelegate_2) == 0x000058, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, K2Node_CreateDelegate_OutputDelegate_3) == 0x000068, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_AddCmpgnLvl, CallFunc_AddChild_ReturnValue) == 0x000078, "Member 'WBP_EditorLoad_C_AddCmpgnLvl::CallFunc_AddChild_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.BuildCampaignList
// 0x0078 (0x0078 - 0x0000)
struct WBP_EditorLoad_C_BuildCampaignList final
{
public:
	class UWBP_AdamButton_C*                      CallFunc_Create_ReturnValue;                       // 0x0000(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_AdamButton_C* me)>  K2Node_CreateDelegate_OutputDelegate;              // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UCustomCampaign*>                CallFunc_GetFoundCampaigns_ReturnValue;            // 0x0038(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCustomCampaign*                        CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0060(0x0018)()
};
static_assert(alignof(WBP_EditorLoad_C_BuildCampaignList) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_BuildCampaignList");
static_assert(sizeof(WBP_EditorLoad_C_BuildCampaignList) == 0x000078, "Wrong size on WBP_EditorLoad_C_BuildCampaignList");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Create_ReturnValue) == 0x000000, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, Temp_int_Array_Index_Variable) == 0x000008, "Member 'WBP_EditorLoad_C_BuildCampaignList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'WBP_EditorLoad_C_BuildCampaignList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, K2Node_CreateDelegate_OutputDelegate) == 0x000014, "Member 'WBP_EditorLoad_C_BuildCampaignList::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_AddChild_ReturnValue) == 0x000028, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_GetTYVCGameMode_NewParam) == 0x000030, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_GetFoundCampaigns_ReturnValue) == 0x000038, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_GetFoundCampaigns_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Array_Length_ReturnValue) == 0x000048, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Array_Get_Item) == 0x000050, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Less_IntInt_ReturnValue) == 0x000058, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_BuildCampaignList, CallFunc_Conv_StringToText_ReturnValue) == 0x000060, "Member 'WBP_EditorLoad_C_BuildCampaignList::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.Load Campaign
// 0x0030 (0x0030 - 0x0000)
struct WBP_EditorLoad_C_Load_Campaign final
{
public:
	class UWBP_AdamButton_C*                      me;                                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCustomCampaign*                        K2Node_DynamicCast_AsCustom_Campaign;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
};
static_assert(alignof(WBP_EditorLoad_C_Load_Campaign) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_Load_Campaign");
static_assert(sizeof(WBP_EditorLoad_C_Load_Campaign) == 0x000030, "Wrong size on WBP_EditorLoad_C_Load_Campaign");
static_assert(offsetof(WBP_EditorLoad_C_Load_Campaign, me) == 0x000000, "Member 'WBP_EditorLoad_C_Load_Campaign::me' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Load_Campaign, K2Node_DynamicCast_AsCustom_Campaign) == 0x000008, "Member 'WBP_EditorLoad_C_Load_Campaign::K2Node_DynamicCast_AsCustom_Campaign' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Load_Campaign, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'WBP_EditorLoad_C_Load_Campaign::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Load_Campaign, CallFunc_Conv_StringToText_ReturnValue) == 0x000018, "Member 'WBP_EditorLoad_C_Load_Campaign::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.DeleteCampaignLevel
// 0x0008 (0x0008 - 0x0000)
struct WBP_EditorLoad_C_DeleteCampaignLevel final
{
public:
	class UWBP_CmpgnLvl_C*                        NewParam;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_DeleteCampaignLevel) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_DeleteCampaignLevel");
static_assert(sizeof(WBP_EditorLoad_C_DeleteCampaignLevel) == 0x000008, "Wrong size on WBP_EditorLoad_C_DeleteCampaignLevel");
static_assert(offsetof(WBP_EditorLoad_C_DeleteCampaignLevel, NewParam) == 0x000000, "Member 'WBP_EditorLoad_C_DeleteCampaignLevel::NewParam' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.MoveUp
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_EditorLoad_C_MoveUp final
{
public:
	class UWBP_CmpgnLvl_C*                        me;                                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DesiredIndex;                                      // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_CmpgnLvl_C*>                List;                                              // 0x0010(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CmpgnLvl_C*                        CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0058(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_GetChildIndex_ReturnValue;                // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item_1;                         // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7B[0x5];                                       // 0x007B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CmpgnLvl_C*                        K2Node_DynamicCast_AsWBP_Cmpgn_Lvl;                // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_EditorLoad_C_MoveUp) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_MoveUp");
static_assert(sizeof(WBP_EditorLoad_C_MoveUp) == 0x0000A0, "Wrong size on WBP_EditorLoad_C_MoveUp");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, me) == 0x000000, "Member 'WBP_EditorLoad_C_MoveUp::me' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, DesiredIndex) == 0x000008, "Member 'WBP_EditorLoad_C_MoveUp::DesiredIndex' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, List) == 0x000010, "Member 'WBP_EditorLoad_C_MoveUp::List' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_EditorLoad_C_MoveUp::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_EditorLoad_C_MoveUp::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, Temp_int_Array_Index_Variable_1) == 0x00002C, "Member 'WBP_EditorLoad_C_MoveUp::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, Temp_int_Loop_Counter_Variable_1) == 0x000030, "Member 'WBP_EditorLoad_C_MoveUp::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Array_Get_Item) == 0x000038, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_AddChild_ReturnValue) == 0x000048, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Less_IntInt_ReturnValue) == 0x000050, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Add_IntInt_ReturnValue_1) == 0x000054, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_GetAllChildren_ReturnValue) == 0x000058, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_GetChildIndex_ReturnValue) == 0x000068, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_GetChildIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Array_Get_Item_1) == 0x000070, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000078, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000079, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Not_PreBool_ReturnValue) == 0x00007A, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, K2Node_DynamicCast_AsWBP_Cmpgn_Lvl) == 0x000080, "Member 'WBP_EditorLoad_C_MoveUp::K2Node_DynamicCast_AsWBP_Cmpgn_Lvl' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, K2Node_DynamicCast_bSuccess) == 0x000088, "Member 'WBP_EditorLoad_C_MoveUp::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Array_Add_ReturnValue) == 0x00008C, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Add_IntInt_ReturnValue_2) == 0x000090, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Array_Length_ReturnValue_1) == 0x000094, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveUp, CallFunc_Less_IntInt_ReturnValue_1) == 0x000098, "Member 'WBP_EditorLoad_C_MoveUp::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.MoveDown
// 0x0098 (0x0098 - 0x0000)
struct WBP_EditorLoad_C_MoveDown final
{
public:
	class UWBP_CmpgnLvl_C*                        NewParam;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWBP_CmpgnLvl_C*>                List;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         DesiredIndex;                                      // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_CmpgnLvl_C*                        CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0050(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item_1;                         // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_75[0x3];                                       // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CmpgnLvl_C*                        K2Node_DynamicCast_AsWBP_Cmpgn_Lvl;                // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildIndex_ReturnValue;                // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x2];                                       // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_MoveDown) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_MoveDown");
static_assert(sizeof(WBP_EditorLoad_C_MoveDown) == 0x000098, "Wrong size on WBP_EditorLoad_C_MoveDown");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, NewParam) == 0x000000, "Member 'WBP_EditorLoad_C_MoveDown::NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, List) == 0x000008, "Member 'WBP_EditorLoad_C_MoveDown::List' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, DesiredIndex) == 0x000018, "Member 'WBP_EditorLoad_C_MoveDown::DesiredIndex' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'WBP_EditorLoad_C_MoveDown::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, Temp_int_Array_Index_Variable) == 0x000024, "Member 'WBP_EditorLoad_C_MoveDown::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, Temp_int_Array_Index_Variable_1) == 0x000028, "Member 'WBP_EditorLoad_C_MoveDown::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, Temp_int_Loop_Counter_Variable_1) == 0x00002C, "Member 'WBP_EditorLoad_C_MoveDown::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Array_Get_Item) == 0x000030, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_AddChild_ReturnValue) == 0x000040, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Less_IntInt_ReturnValue) == 0x000048, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Add_IntInt_ReturnValue_1) == 0x00004C, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_GetAllChildren_ReturnValue) == 0x000050, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_GetChildrenCount_ReturnValue) == 0x000060, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Array_Get_Item_1) == 0x000068, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Subtract_IntInt_ReturnValue) == 0x000070, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000074, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, K2Node_DynamicCast_AsWBP_Cmpgn_Lvl) == 0x000078, "Member 'WBP_EditorLoad_C_MoveDown::K2Node_DynamicCast_AsWBP_Cmpgn_Lvl' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, K2Node_DynamicCast_bSuccess) == 0x000080, "Member 'WBP_EditorLoad_C_MoveDown::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Not_PreBool_ReturnValue) == 0x000081, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Array_Add_ReturnValue) == 0x000084, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Array_Length_ReturnValue_1) == 0x000088, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_GetChildIndex_ReturnValue) == 0x00008C, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_GetChildIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Less_IntInt_ReturnValue_1) == 0x000090, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000091, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_MoveDown, CallFunc_Add_IntInt_ReturnValue_2) == 0x000094, "Member 'WBP_EditorLoad_C_MoveDown::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.Get Campaign
// 0x0208 (0x0208 - 0x0000)
struct WBP_EditorLoad_C_Get_Campaign final
{
public:
	struct FCustomCampaignStruct                  NewParam;                                          // 0x0000(0x0088)(Parm, OutParm)
	int32                                         FoundScreenIdx;                                    // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UArcadeLevelAsset*                      CallFunc_GetLvlInfo_OutLvl;                        // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCustomCampaignText                    CallFunc_GetLvlInfo_OutTet;                        // 0x00A0(0x0010)()
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x00B0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x00D8(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x00F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FCustomCampaignStruct                  K2Node_MakeStruct_CustomCampaignStruct;            // 0x0100(0x0088)()
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0188(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CmpgnLvl_C*                        K2Node_DynamicCast_AsWBP_Cmpgn_Lvl;                // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UArcadeLevelAsset*                      CallFunc_GetLvlInfo_OutLvl_1;                      // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCustomCampaignText                    CallFunc_GetLvlInfo_OutTet_1;                      // 0x01C8(0x0010)()
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1DC[0x4];                                      // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UArcadeLevelAssetWorkshop*              K2Node_DynamicCast_AsArcade_Level_Asset_Workshop;  // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x3];                                      // 0x01E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x01F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_EditorLoad_C_Get_Campaign) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_Get_Campaign");
static_assert(sizeof(WBP_EditorLoad_C_Get_Campaign) == 0x000208, "Wrong size on WBP_EditorLoad_C_Get_Campaign");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, NewParam) == 0x000000, "Member 'WBP_EditorLoad_C_Get_Campaign::NewParam' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, FoundScreenIdx) == 0x000088, "Member 'WBP_EditorLoad_C_Get_Campaign::FoundScreenIdx' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, Temp_int_Array_Index_Variable) == 0x00008C, "Member 'WBP_EditorLoad_C_Get_Campaign::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, Temp_int_Loop_Counter_Variable) == 0x000090, "Member 'WBP_EditorLoad_C_Get_Campaign::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Add_IntInt_ReturnValue) == 0x000094, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetLvlInfo_OutLvl) == 0x000098, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetLvlInfo_OutLvl' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetLvlInfo_OutTet) == 0x0000A0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetLvlInfo_OutTet' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetText_ReturnValue) == 0x0000B0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Conv_TextToString_ReturnValue) == 0x0000C8, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetText_ReturnValue_1) == 0x0000D8, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Conv_TextToString_ReturnValue_1) == 0x0000F0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, K2Node_MakeStruct_CustomCampaignStruct) == 0x000100, "Member 'WBP_EditorLoad_C_Get_Campaign::K2Node_MakeStruct_CustomCampaignStruct' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetAllChildren_ReturnValue) == 0x000188, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Array_Length_ReturnValue) == 0x000198, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Array_Get_Item) == 0x0001A0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Less_IntInt_ReturnValue) == 0x0001A8, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, K2Node_DynamicCast_AsWBP_Cmpgn_Lvl) == 0x0001B0, "Member 'WBP_EditorLoad_C_Get_Campaign::K2Node_DynamicCast_AsWBP_Cmpgn_Lvl' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, K2Node_DynamicCast_bSuccess) == 0x0001B8, "Member 'WBP_EditorLoad_C_Get_Campaign::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetLvlInfo_OutLvl_1) == 0x0001C0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetLvlInfo_OutLvl_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_GetLvlInfo_OutTet_1) == 0x0001C8, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_GetLvlInfo_OutTet_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Array_Add_ReturnValue) == 0x0001D8, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, K2Node_DynamicCast_AsArcade_Level_Asset_Workshop) == 0x0001E0, "Member 'WBP_EditorLoad_C_Get_Campaign::K2Node_DynamicCast_AsArcade_Level_Asset_Workshop' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, K2Node_DynamicCast_bSuccess_1) == 0x0001E8, "Member 'WBP_EditorLoad_C_Get_Campaign::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Array_Add_ReturnValue_1) == 0x0001EC, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Conv_TextToString_ReturnValue_2) == 0x0001F0, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_Get_Campaign, CallFunc_Array_Add_ReturnValue_2) == 0x000200, "Member 'WBP_EditorLoad_C_Get_Campaign::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");

// Function WBP_EditorLoad.WBP_EditorLoad_C.SetScreen
// 0x0050 (0x0050 - 0x0000)
struct WBP_EditorLoad_C_SetScreen final
{
public:
	class UWBP_CmpgnLvl_C*                        This;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CmpgnLvl_C*                        K2Node_DynamicCast_AsWBP_Cmpgn_Lvl;                // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_EditorLoad_C_SetScreen) == 0x000008, "Wrong alignment on WBP_EditorLoad_C_SetScreen");
static_assert(sizeof(WBP_EditorLoad_C_SetScreen) == 0x000050, "Wrong size on WBP_EditorLoad_C_SetScreen");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, This) == 0x000000, "Member 'WBP_EditorLoad_C_SetScreen::This' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, Temp_int_Array_Index_Variable) == 0x000008, "Member 'WBP_EditorLoad_C_SetScreen::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'WBP_EditorLoad_C_SetScreen::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_GetAllChildren_ReturnValue) == 0x000018, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_Array_Get_Item) == 0x000030, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, K2Node_DynamicCast_AsWBP_Cmpgn_Lvl) == 0x000040, "Member 'WBP_EditorLoad_C_SetScreen::K2Node_DynamicCast_AsWBP_Cmpgn_Lvl' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'WBP_EditorLoad_C_SetScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_EditorLoad_C_SetScreen, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000049, "Member 'WBP_EditorLoad_C_SetScreen::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");

}

