#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TitleFlash

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "MediaUtils_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "InputCore_structs.hpp"
#include "ThankYouVeryCool_structs.hpp"


namespace SDK::Params
{

// Function WBP_TitleFlash.WBP_TitleFlash_C.ExecuteUbergraph_WBP_TitleFlash
// 0x0120 (0x0120 - 0x0000)
struct WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatformName                                 Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_6;                               // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_7;                               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_8;                               // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_9;                               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_10;                              // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_11;                              // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_12;                              // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_13;                              // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue;                         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Play_ReturnValue_1;                       // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFileMediaSource*                       K2Node_CustomEvent_InSource;                       // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFileMediaSource*                       CallFunc_GetOverrideVideo_OverrideSource;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MenuPawn_C*                         K2Node_DynamicCast_AsBP_Menu_Pawn;                 // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFileMediaSource*                       CallFunc_UpdateVideoSource_OutputSource;           // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMediaPlayer*                           CallFunc_GetMediaPlayer_ReturnValue;               // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue_2;                       // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_1;               // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam_2;               // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPlatformName                                 CallFunc_GetCurrentPlatform_ReturnValue;           // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C2[0x2];                                       // 0x00C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMediaPlayerTrackOptions               K2Node_MakeStruct_MediaPlayerTrackOptions;         // 0x00C8(0x001C)(NoDestructor)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMediaPlayerOptions                    K2Node_MakeStruct_MediaPlayerOptions;              // 0x00E8(0x0030)(NoDestructor)
	bool                                          CallFunc_OpenSourceLatent_bSuccess;                // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash");
static_assert(sizeof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash) == 0x000120, "Wrong size on WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, EntryPoint) == 0x000000, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_byte_Variable) == 0x000005, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable) == 0x000018, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_1) == 0x00001C, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_2) == 0x000020, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_3) == 0x000024, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_4) == 0x000028, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_5) == 0x00002C, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_6) == 0x000030, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_7) == 0x000034, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_8) == 0x000038, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_8' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_9) == 0x00003C, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_9' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_10) == 0x000040, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_10' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_11) == 0x000044, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_11' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_12) == 0x000048, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_12' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, Temp_int_Variable_13) == 0x00004C, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::Temp_int_Variable_13' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_Play_ReturnValue) == 0x000050, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_Play_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_Play_ReturnValue_1) == 0x000051, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_Play_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_CustomEvent_InSource) == 0x000058, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_CustomEvent_InSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetTYVCGameMode_NewParam) == 0x000060, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetOverrideVideo_OverrideSource) == 0x000068, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetOverrideVideo_OverrideSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_DynamicCast_AsBP_Menu_Pawn) == 0x000070, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_DynamicCast_AsBP_Menu_Pawn' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_DynamicCast_bSuccess) == 0x000078, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_UpdateVideoSource_OutputSource) == 0x000080, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_UpdateVideoSource_OutputSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_Event_IsDesignTime) == 0x000088, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetMediaPlayer_ReturnValue) == 0x000090, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetMediaPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetPlayerController_ReturnValue) == 0x000098, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_Play_ReturnValue_2) == 0x0000A0, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_Play_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetPlayerController_ReturnValue_1) == 0x0000A8, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetTYVCGameMode_NewParam_1) == 0x0000B0, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetTYVCGameMode_NewParam_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetTYVCGameMode_NewParam_2) == 0x0000B8, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetTYVCGameMode_NewParam_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_IsPlatform_ReturnValue) == 0x0000C0, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_GetCurrentPlatform_ReturnValue) == 0x0000C1, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_GetCurrentPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_Select_Default) == 0x0000C4, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_MakeStruct_MediaPlayerTrackOptions) == 0x0000C8, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_MakeStruct_MediaPlayerTrackOptions' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, K2Node_MakeStruct_MediaPlayerOptions) == 0x0000E8, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::K2Node_MakeStruct_MediaPlayerOptions' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash, CallFunc_OpenSourceLatent_bSuccess) == 0x000118, "Member 'WBP_TitleFlash_C_ExecuteUbergraph_WBP_TitleFlash::CallFunc_OpenSourceLatent_bSuccess' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_TitleFlash_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_TitleFlash_C_PreConstruct");
static_assert(sizeof(WBP_TitleFlash_C_PreConstruct) == 0x000001, "Wrong size on WBP_TitleFlash_C_PreConstruct");
static_assert(offsetof(WBP_TitleFlash_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_TitleFlash_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.PlayVideoEvent
// 0x0008 (0x0008 - 0x0000)
struct WBP_TitleFlash_C_PlayVideoEvent final
{
public:
	class UFileMediaSource*                       InSource;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TitleFlash_C_PlayVideoEvent) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_PlayVideoEvent");
static_assert(sizeof(WBP_TitleFlash_C_PlayVideoEvent) == 0x000008, "Wrong size on WBP_TitleFlash_C_PlayVideoEvent");
static_assert(offsetof(WBP_TitleFlash_C_PlayVideoEvent, InSource) == 0x000000, "Member 'WBP_TitleFlash_C_PlayVideoEvent::InSource' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.OnKeyDown
// 0x0288 (0x0288 - 0x0000)
struct WBP_TitleFlash_C_OnKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0128(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetKey_ReturnValue_1;                     // 0x0148(0x0018)(HasGetValueTypeHash)
	struct FKey                                   CallFunc_GetKey_ReturnValue_2;                     // 0x0160(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_2;          // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x017A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_17B[0x5];                                      // 0x017B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetKey_ReturnValue_3;                     // 0x0180(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetKey_ReturnValue_4;                     // 0x01A0(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue_1;           // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x01BB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x01BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1BD[0x3];                                      // 0x01BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x01C8(0x00B8)()
	bool                                          CallFunc_IsPaused_ReturnValue;                     // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Play_ReturnValue;                         // 0x0281(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Pause_ReturnValue;                        // 0x0282(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_OnKeyDown) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_OnKeyDown");
static_assert(sizeof(WBP_TitleFlash_C_OnKeyDown) == 0x000288, "Wrong size on WBP_TitleFlash_C_OnKeyDown");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, MyGeometry) == 0x000000, "Member 'WBP_TitleFlash_C_OnKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, InKeyEvent) == 0x000038, "Member 'WBP_TitleFlash_C_OnKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, ReturnValue) == 0x000070, "Member 'WBP_TitleFlash_C_OnKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetKey_ReturnValue) == 0x000128, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_IsValid_ReturnValue) == 0x000140, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x000141, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetKey_ReturnValue_1) == 0x000148, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetKey_ReturnValue_2) == 0x000160, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetKey_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x000178, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_2) == 0x000179, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_BooleanOR_ReturnValue) == 0x00017A, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetKey_ReturnValue_3) == 0x000180, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetKey_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_BooleanOR_ReturnValue_1) == 0x000198, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_Key_IsGamepadKey_ReturnValue) == 0x000199, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_Key_IsGamepadKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetKey_ReturnValue_4) == 0x0001A0, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetKey_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_Key_IsGamepadKey_ReturnValue_1) == 0x0001B8, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_Key_IsGamepadKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_IsValid_ReturnValue_1) == 0x0001B9, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x0001BA, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_BooleanOR_ReturnValue_2) == 0x0001BB, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_IsPlatform_ReturnValue) == 0x0001BC, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_GetPlayerController_ReturnValue) == 0x0001C0, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_Handled_ReturnValue) == 0x0001C8, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_IsPaused_ReturnValue) == 0x000280, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_IsPaused_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_Play_ReturnValue) == 0x000281, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_Play_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_OnKeyDown, CallFunc_Pause_ReturnValue) == 0x000282, "Member 'WBP_TitleFlash_C_OnKeyDown::CallFunc_Pause_ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.DoResumeButtonNavigationDown
// 0x0010 (0x0010 - 0x0000)
struct WBP_TitleFlash_C_DoResumeButtonNavigationDown final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TitleFlash_C_DoResumeButtonNavigationDown) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_DoResumeButtonNavigationDown");
static_assert(sizeof(WBP_TitleFlash_C_DoResumeButtonNavigationDown) == 0x000010, "Wrong size on WBP_TitleFlash_C_DoResumeButtonNavigationDown");
static_assert(offsetof(WBP_TitleFlash_C_DoResumeButtonNavigationDown, Navigation_0) == 0x000000, "Member 'WBP_TitleFlash_C_DoResumeButtonNavigationDown::Navigation_0' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_DoResumeButtonNavigationDown, ReturnValue) == 0x000008, "Member 'WBP_TitleFlash_C_DoResumeButtonNavigationDown::ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.DoSkipButtonNavigation
// 0x0018 (0x0018 - 0x0000)
struct WBP_TitleFlash_C_DoSkipButtonNavigation final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_DoSkipButtonNavigation) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_DoSkipButtonNavigation");
static_assert(sizeof(WBP_TitleFlash_C_DoSkipButtonNavigation) == 0x000018, "Wrong size on WBP_TitleFlash_C_DoSkipButtonNavigation");
static_assert(offsetof(WBP_TitleFlash_C_DoSkipButtonNavigation, Navigation_0) == 0x000000, "Member 'WBP_TitleFlash_C_DoSkipButtonNavigation::Navigation_0' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_DoSkipButtonNavigation, ReturnValue) == 0x000008, "Member 'WBP_TitleFlash_C_DoSkipButtonNavigation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_DoSkipButtonNavigation, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000010, "Member 'WBP_TitleFlash_C_DoSkipButtonNavigation::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.DoQuitButtonNavigationUp
// 0x0010 (0x0010 - 0x0000)
struct WBP_TitleFlash_C_DoQuitButtonNavigationUp final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TitleFlash_C_DoQuitButtonNavigationUp) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_DoQuitButtonNavigationUp");
static_assert(sizeof(WBP_TitleFlash_C_DoQuitButtonNavigationUp) == 0x000010, "Wrong size on WBP_TitleFlash_C_DoQuitButtonNavigationUp");
static_assert(offsetof(WBP_TitleFlash_C_DoQuitButtonNavigationUp, Navigation_0) == 0x000000, "Member 'WBP_TitleFlash_C_DoQuitButtonNavigationUp::Navigation_0' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_DoQuitButtonNavigationUp, ReturnValue) == 0x000008, "Member 'WBP_TitleFlash_C_DoQuitButtonNavigationUp::ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.UpdateVideoSource
// 0x0020 (0x0020 - 0x0000)
struct WBP_TitleFlash_C_UpdateVideoSource final
{
public:
	class UFileMediaSource*                       InputSource;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFileMediaSource*                       OutputSource;                                      // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_4;    // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_5;    // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_6;    // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlatform_ReturnValue_1;                 // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_UpdateVideoSource) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_UpdateVideoSource");
static_assert(sizeof(WBP_TitleFlash_C_UpdateVideoSource) == 0x000020, "Wrong size on WBP_TitleFlash_C_UpdateVideoSource");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, InputSource) == 0x000000, "Member 'WBP_TitleFlash_C_UpdateVideoSource::InputSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, OutputSource) == 0x000008, "Member 'WBP_TitleFlash_C_UpdateVideoSource::OutputSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000010, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000011, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000012, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x000013, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_4) == 0x000014, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_5) == 0x000015, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_EqualEqual_ObjectObject_ReturnValue_6) == 0x000016, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_EqualEqual_ObjectObject_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_IsPlatform_ReturnValue) == 0x000017, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_IsPlatform_ReturnValue_1) == 0x000018, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_IsPlatform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_UpdateVideoSource, CallFunc_BooleanOR_ReturnValue) == 0x000019, "Member 'WBP_TitleFlash_C_UpdateVideoSource::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.PlaySwitchAndXboxOneAudio
// 0x0070 (0x0070 - 0x0000)
struct WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio final
{
public:
	class UFileMediaSource*                       InputSource;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             SoundToPlay;                                       // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_4;    // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0xB];                                       // 0x0015(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0020(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_5;    // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_SwitchMovieAudio_C*                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlatform_ReturnValue;                   // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_6;    // 0x006B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlatform_ReturnValue_1;                 // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x006D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio) == 0x000010, "Wrong alignment on WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio");
static_assert(sizeof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio) == 0x000070, "Wrong size on WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, InputSource) == 0x000000, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::InputSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, SoundToPlay) == 0x000008, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::SoundToPlay' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000010, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000011, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000012, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x000013, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_4) == 0x000014, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_MakeTransform_ReturnValue) == 0x000020, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_5) == 0x000050, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000058, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_FinishSpawningActor_ReturnValue) == 0x000060, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_IsPlatform_ReturnValue) == 0x000068, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_IsPlatform_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_IsValid_ReturnValue) == 0x000069, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_Not_PreBool_ReturnValue) == 0x00006A, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_EqualEqual_ObjectObject_ReturnValue_6) == 0x00006B, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_EqualEqual_ObjectObject_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_IsPlatform_ReturnValue_1) == 0x00006C, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_IsPlatform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio, CallFunc_BooleanOR_ReturnValue) == 0x00006D, "Member 'WBP_TitleFlash_C_PlaySwitchAndXboxOneAudio::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function WBP_TitleFlash.WBP_TitleFlash_C.GetOverrideVideo
// 0x0040 (0x0040 - 0x0000)
struct WBP_TitleFlash_C_GetOverrideVideo final
{
public:
	class UFileMediaSource*                       RegularSource;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFileMediaSource*                       OverrideSource;                                    // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AThankYouVeryCoolGameMode*              K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetVideoCutscene_ReturnValue;             // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TitleFlash_C_GetOverrideVideo) == 0x000008, "Wrong alignment on WBP_TitleFlash_C_GetOverrideVideo");
static_assert(sizeof(WBP_TitleFlash_C_GetOverrideVideo) == 0x000040, "Wrong size on WBP_TitleFlash_C_GetOverrideVideo");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, RegularSource) == 0x000000, "Member 'WBP_TitleFlash_C_GetOverrideVideo::RegularSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, OverrideSource) == 0x000008, "Member 'WBP_TitleFlash_C_GetOverrideVideo::OverrideSource' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, CallFunc_GetGameMode_ReturnValue) == 0x000010, "Member 'WBP_TitleFlash_C_GetOverrideVideo::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode) == 0x000018, "Member 'WBP_TitleFlash_C_GetOverrideVideo::K2Node_DynamicCast_AsThank_You_Very_Cool_Game_Mode' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'WBP_TitleFlash_C_GetOverrideVideo::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, CallFunc_GetVideoCutscene_ReturnValue) == 0x000028, "Member 'WBP_TitleFlash_C_GetOverrideVideo::CallFunc_GetVideoCutscene_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TitleFlash_C_GetOverrideVideo, K2Node_SwitchString_CmpSuccess) == 0x000038, "Member 'WBP_TitleFlash_C_GetOverrideVideo::K2Node_SwitchString_CmpSuccess' has a wrong offset!");

}

