#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WeaponSelect

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_WeaponSelect.WBP_WeaponSelect_C
// 0x0098 (0x02F8 - 0x0260)
class UWBP_WeaponSelect_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           fillme;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_69;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         Info;                                              // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URetainerBox*                           RetainerBox_0;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_WorldButtons_C*                    ShuffleBtn;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FText DisplayName, class UClass* WeaponBase)> WeaponSelected;                                    // 0x0298(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class AWeaponBase*                            Weapon_Base;                                       // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              GoBack;                                            // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              ArmCannonSelected;                                 // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UClass*>                         Weapons;                                           // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UWBP_LockedLevel_C*>             RandomList;                                        // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UWBP_LockedLevel_C*                     RandSelect;                                        // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_WeaponSelect(int32 EntryPoint);
	void BndEvt__WBP_WeaponSelect_ShuffleBtn_K2Node_ComponentBoundEvent_0_Pressed__DelegateSignature(EVoxelEditMod OutNav);
	void OnWeaponClicked(class UClass* Weapon, class UWBP_LockedLevel_C* SelfReference);
	void OnSelectionHovered(class UClass* Weapon, class UWBP_LockedLevel_C* SelfReference);
	void BndEvt__ArmCannonButton_K2Node_ComponentBoundEvent_18_OnClickedForWeapon__DelegateSignature(class UClass* Weapon, class UWBP_LockedLevel_C* SelfReference);
	void BndEvt__NoneButton_K2Node_ComponentBoundEvent_14_OnClickedForWeapon__DelegateSignature(class UClass* Weapon, class UWBP_LockedLevel_C* SelfReference);
	void BndEvt__ArmCannonButton_K2Node_ComponentBoundEvent_12_OnPressed__DelegateSignature();
	void BndEvt__NoneButton_K2Node_ComponentBoundEvent_11_OnPressed__DelegateSignature();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void Untogglell();
	void SetToggled(class UClass* WeaponClass, class UWBP_LockedLevel_C** Selected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_WeaponSelect_C">();
	}
	static class UWBP_WeaponSelect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WeaponSelect_C>();
	}
};
static_assert(alignof(UWBP_WeaponSelect_C) == 0x000008, "Wrong alignment on UWBP_WeaponSelect_C");
static_assert(sizeof(UWBP_WeaponSelect_C) == 0x0002F8, "Wrong size on UWBP_WeaponSelect_C");
static_assert(offsetof(UWBP_WeaponSelect_C, UberGraphFrame) == 0x000260, "Member 'UWBP_WeaponSelect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, fillme) == 0x000268, "Member 'UWBP_WeaponSelect_C::fillme' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, Image_0) == 0x000270, "Member 'UWBP_WeaponSelect_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, Image_69) == 0x000278, "Member 'UWBP_WeaponSelect_C::Image_69' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, Info) == 0x000280, "Member 'UWBP_WeaponSelect_C::Info' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, RetainerBox_0) == 0x000288, "Member 'UWBP_WeaponSelect_C::RetainerBox_0' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, ShuffleBtn) == 0x000290, "Member 'UWBP_WeaponSelect_C::ShuffleBtn' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, WeaponSelected) == 0x000298, "Member 'UWBP_WeaponSelect_C::WeaponSelected' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, Weapon_Base) == 0x0002A8, "Member 'UWBP_WeaponSelect_C::Weapon_Base' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, GoBack) == 0x0002B0, "Member 'UWBP_WeaponSelect_C::GoBack' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, ArmCannonSelected) == 0x0002C0, "Member 'UWBP_WeaponSelect_C::ArmCannonSelected' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, Weapons) == 0x0002D0, "Member 'UWBP_WeaponSelect_C::Weapons' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, RandomList) == 0x0002E0, "Member 'UWBP_WeaponSelect_C::RandomList' has a wrong offset!");
static_assert(offsetof(UWBP_WeaponSelect_C, RandSelect) == 0x0002F0, "Member 'UWBP_WeaponSelect_C::RandSelect' has a wrong offset!");

}

