#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EditorMainNav

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EditorMainNav.WBP_EditorMainNav_C
// 0x0530 (0x0790 - 0x0260)
class UWBP_EditorMainNav_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_24;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Hatching;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 InnerIcon;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(EEditorMainNav OutNav)> Pressed;                                           // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FButtonStyle                           UnselectedStyle;                                   // 0x0290(0x0278)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FButtonStyle                           SelectedStyle;                                     // 0x0508(0x0278)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UTexture2D*                             IconTexture;                                       // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	EEditorMainNav                                MyNav;                                             // 0x0788(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_EditorMainNav(int32 EntryPoint);
	void SetSelected(bool bSelected);
	void BndEvt__WBP_EditorMainNav_Button_24_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_EditorMainNav_Button_24_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_EditorMainNav_Button_24_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_EditorMainNav_C">();
	}
	static class UWBP_EditorMainNav_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EditorMainNav_C>();
	}
};
static_assert(alignof(UWBP_EditorMainNav_C) == 0x000008, "Wrong alignment on UWBP_EditorMainNav_C");
static_assert(sizeof(UWBP_EditorMainNav_C) == 0x000790, "Wrong size on UWBP_EditorMainNav_C");
static_assert(offsetof(UWBP_EditorMainNav_C, UberGraphFrame) == 0x000260, "Member 'UWBP_EditorMainNav_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, Button_24) == 0x000268, "Member 'UWBP_EditorMainNav_C::Button_24' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, Hatching) == 0x000270, "Member 'UWBP_EditorMainNav_C::Hatching' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, InnerIcon) == 0x000278, "Member 'UWBP_EditorMainNav_C::InnerIcon' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, Pressed) == 0x000280, "Member 'UWBP_EditorMainNav_C::Pressed' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, UnselectedStyle) == 0x000290, "Member 'UWBP_EditorMainNav_C::UnselectedStyle' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, SelectedStyle) == 0x000508, "Member 'UWBP_EditorMainNav_C::SelectedStyle' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, IconTexture) == 0x000780, "Member 'UWBP_EditorMainNav_C::IconTexture' has a wrong offset!");
static_assert(offsetof(UWBP_EditorMainNav_C, MyNav) == 0x000788, "Member 'UWBP_EditorMainNav_C::MyNav' has a wrong offset!");

}

