#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CannonShot

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CannonShot.WBP_CannonShot_C.SetFull
// 0x0010 (0x0010 - 0x0000)
struct WBP_CannonShot_C_SetFull final
{
public:
	bool                                          IsFull;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_CannonShot_C_SetFull) == 0x000004, "Wrong alignment on WBP_CannonShot_C_SetFull");
static_assert(sizeof(WBP_CannonShot_C_SetFull) == 0x000010, "Wrong size on WBP_CannonShot_C_SetFull");
static_assert(offsetof(WBP_CannonShot_C_SetFull, IsFull) == 0x000000, "Member 'WBP_CannonShot_C_SetFull::IsFull' has a wrong offset!");
static_assert(offsetof(WBP_CannonShot_C_SetFull, Temp_bool_Variable) == 0x000001, "Member 'WBP_CannonShot_C_SetFull::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CannonShot_C_SetFull, Temp_int_Variable) == 0x000004, "Member 'WBP_CannonShot_C_SetFull::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CannonShot_C_SetFull, Temp_int_Variable_1) == 0x000008, "Member 'WBP_CannonShot_C_SetFull::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_CannonShot_C_SetFull, K2Node_Select_Default) == 0x00000C, "Member 'WBP_CannonShot_C_SetFull::K2Node_Select_Default' has a wrong offset!");

}

