#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PatchNum

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PatchNum.WBP_PatchNum_C
// 0x0020 (0x0280 - 0x0260)
class UWBP_PatchNum_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             BuildInfo_1;                                       // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Pre;                                               // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Suf;                                               // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PatchNum(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PatchNum_C">();
	}
	static class UWBP_PatchNum_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PatchNum_C>();
	}
};
static_assert(alignof(UWBP_PatchNum_C) == 0x000008, "Wrong alignment on UWBP_PatchNum_C");
static_assert(sizeof(UWBP_PatchNum_C) == 0x000280, "Wrong size on UWBP_PatchNum_C");
static_assert(offsetof(UWBP_PatchNum_C, UberGraphFrame) == 0x000260, "Member 'UWBP_PatchNum_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PatchNum_C, BuildInfo_1) == 0x000268, "Member 'UWBP_PatchNum_C::BuildInfo_1' has a wrong offset!");
static_assert(offsetof(UWBP_PatchNum_C, Pre) == 0x000270, "Member 'UWBP_PatchNum_C::Pre' has a wrong offset!");
static_assert(offsetof(UWBP_PatchNum_C, Suf) == 0x000278, "Member 'UWBP_PatchNum_C::Suf' has a wrong offset!");

}

