#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RogueMain

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RogueMain.WBP_RogueMain_C
// 0x0090 (0x02F0 - 0x0260)
class UWBP_RogueMain_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AdamButton_C*                      AdvancedBtn;                                       // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      CollectionBtn;                                     // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      ContBtn;                                           // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      CosmeticsBtn;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             den;                                               // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DifficultyDescription;                             // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             LTS;                                               // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Num;                                               // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      PlayBtn;                                           // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             RC;                                                // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             Secondary;                                         // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock;                                         // 0x02C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_2;                                       // 0x02C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_4;                                       // 0x02D0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_0;                                  // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ToFocus;                                           // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bWannaContinue;                                    // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_RogueMain(int32 EntryPoint);
	void BndEvt__WBP_RogueMain_ContBtn_K2Node_ComponentBoundEvent_8_OnPressed__DelegateSignature();
	void DoPlay();
	void BndEvt__WBP_RogueMain_AdvancedBtn_K2Node_ComponentBoundEvent_7_OnHovered__DelegateSignature();
	void BndEvt__WBP_RogueMain_CosmeticsBtn_K2Node_ComponentBoundEvent_6_OnHovered__DelegateSignature();
	void BndEvt__WBP_RogueMain_CollectionBtn_K2Node_ComponentBoundEvent_5_OnHovered__DelegateSignature();
	void BndEvt__WBP_RogueMain_PlayBtn_K2Node_ComponentBoundEvent_4_OnHovered__DelegateSignature();
	void BndEvt__WBP_RogueMain_WBP_AdamButton_3_K2Node_ComponentBoundEvent_3_OnPressed__DelegateSignature();
	void BndEvt__WBP_RogueMain_WBP_AdamButton_2_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature();
	void Construct();
	void CardPicked_Event_0(class UCardData* Card);
	void BndEvt__WBP_RogueMain_WBP_AdamButton_1_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature();
	void BndEvt__WBP_RogueMain_WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature();
	void CustomEvent_0();
	struct FSlateColor GetColorAndOpacity_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_RogueMain_C">();
	}
	static class UWBP_RogueMain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RogueMain_C>();
	}
};
static_assert(alignof(UWBP_RogueMain_C) == 0x000008, "Wrong alignment on UWBP_RogueMain_C");
static_assert(sizeof(UWBP_RogueMain_C) == 0x0002F0, "Wrong size on UWBP_RogueMain_C");
static_assert(offsetof(UWBP_RogueMain_C, UberGraphFrame) == 0x000260, "Member 'UWBP_RogueMain_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, AdvancedBtn) == 0x000268, "Member 'UWBP_RogueMain_C::AdvancedBtn' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, CollectionBtn) == 0x000270, "Member 'UWBP_RogueMain_C::CollectionBtn' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, ContBtn) == 0x000278, "Member 'UWBP_RogueMain_C::ContBtn' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, CosmeticsBtn) == 0x000280, "Member 'UWBP_RogueMain_C::CosmeticsBtn' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, den) == 0x000288, "Member 'UWBP_RogueMain_C::den' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, DifficultyDescription) == 0x000290, "Member 'UWBP_RogueMain_C::DifficultyDescription' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, LTS) == 0x000298, "Member 'UWBP_RogueMain_C::LTS' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, Num) == 0x0002A0, "Member 'UWBP_RogueMain_C::Num' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, PlayBtn) == 0x0002A8, "Member 'UWBP_RogueMain_C::PlayBtn' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, RC) == 0x0002B0, "Member 'UWBP_RogueMain_C::RC' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, Secondary) == 0x0002B8, "Member 'UWBP_RogueMain_C::Secondary' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, TextBlock) == 0x0002C0, "Member 'UWBP_RogueMain_C::TextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, TextBlock_2) == 0x0002C8, "Member 'UWBP_RogueMain_C::TextBlock_2' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, TextBlock_4) == 0x0002D0, "Member 'UWBP_RogueMain_C::TextBlock_4' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, WidgetSwitcher_0) == 0x0002D8, "Member 'UWBP_RogueMain_C::WidgetSwitcher_0' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, ToFocus) == 0x0002E0, "Member 'UWBP_RogueMain_C::ToFocus' has a wrong offset!");
static_assert(offsetof(UWBP_RogueMain_C, bWannaContinue) == 0x0002E8, "Member 'UWBP_RogueMain_C::bWannaContinue' has a wrong offset!");

}

