#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MusicCombo_2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MusicCombo_2.WBP_MusicCombo_2_C
// 0x0078 (0x02D8 - 0x0260)
class UWBP_MusicCombo_2_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_0;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_31;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           WBP_AdamSmallToggleButton;                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 inString;                                          // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	TSoftObjectPtr<class USoundBase>              MyTrack;                                           // 0x0290(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          In;                                                // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool NewStatus, class UWBP_MusicCombo_2_C* me)> ImPressed;                                         // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          impolay;                                           // 0x02D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_MusicCombo_2(int32 EntryPoint);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void BndEvt__WBP_MusicCombo_2_Button_0_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
	void SetActive(bool bin);
	void BndEvt__WBP_MusicCombo_2_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void Construct();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MusicCombo_2_C">();
	}
	static class UWBP_MusicCombo_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MusicCombo_2_C>();
	}
};
static_assert(alignof(UWBP_MusicCombo_2_C) == 0x000008, "Wrong alignment on UWBP_MusicCombo_2_C");
static_assert(sizeof(UWBP_MusicCombo_2_C) == 0x0002D8, "Wrong size on UWBP_MusicCombo_2_C");
static_assert(offsetof(UWBP_MusicCombo_2_C, UberGraphFrame) == 0x000260, "Member 'UWBP_MusicCombo_2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, Button_0) == 0x000268, "Member 'UWBP_MusicCombo_2_C::Button_0' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, TextBlock_31) == 0x000270, "Member 'UWBP_MusicCombo_2_C::TextBlock_31' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, WBP_AdamSmallToggleButton) == 0x000278, "Member 'UWBP_MusicCombo_2_C::WBP_AdamSmallToggleButton' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, inString) == 0x000280, "Member 'UWBP_MusicCombo_2_C::inString' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, MyTrack) == 0x000290, "Member 'UWBP_MusicCombo_2_C::MyTrack' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, In) == 0x0002B8, "Member 'UWBP_MusicCombo_2_C::In' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, ImPressed) == 0x0002C0, "Member 'UWBP_MusicCombo_2_C::ImPressed' has a wrong offset!");
static_assert(offsetof(UWBP_MusicCombo_2_C, impolay) == 0x0002D0, "Member 'UWBP_MusicCombo_2_C::impolay' has a wrong offset!");

}

