#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RogueEdensysDraw

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_RogueEdensysDraw.WBP_RogueEdensysDraw_C.ExecuteUbergraph_WBP_RogueEdensysDraw
// 0x0030 (0x0030 - 0x0000)
struct WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	class ATYVCGameMode_BP_C*                     CallFunc_GetTYVCGameMode_NewParam;                 // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCardData*                              CallFunc_DrawEdensysCard_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw) == 0x000008, "Wrong alignment on WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw");
static_assert(sizeof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw) == 0x000030, "Wrong size on WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw");
static_assert(offsetof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw, EntryPoint) == 0x000000, "Member 'WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw, CallFunc_GetTYVCGameMode_NewParam) == 0x000020, "Member 'WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw::CallFunc_GetTYVCGameMode_NewParam' has a wrong offset!");
static_assert(offsetof(WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw, CallFunc_DrawEdensysCard_ReturnValue) == 0x000028, "Member 'WBP_RogueEdensysDraw_C_ExecuteUbergraph_WBP_RogueEdensysDraw::CallFunc_DrawEdensysCard_ReturnValue' has a wrong offset!");

}

